#!/usr/bin/env python3
"""Regenerate the reproducible PIC viewer stub and embedded source. No ROM/code downloads."""
import argparse, pathlib, subprocess, tempfile
root = pathlib.Path(__file__).resolve().parent.parent
p = argparse.ArgumentParser();p.add_argument('--prefix', default=str(root/'third_party/vscode-amiga-debug/bin/darwin/opt/bin/m68k-amiga-elf-'));a=p.parse_args()
s = (root/'src/atari/spectrum_viewer.s').read_text()
with tempfile.TemporaryDirectory() as t:
    o=pathlib.Path(t)/'viewer.o';b=pathlib.Path(t)/'viewer.bin'
    subprocess.run([a.prefix+'as','-m68000',str(root/'src/atari/spectrum_viewer.s'),'-o',str(o)],check=True)
    subprocess.run([a.prefix+'ld','-Ttext=0','--oformat=binary',str(o),'-o',str(b)],check=True)
    data=b.read_bytes()
text='// Generated by tools/build-spectrum-runtime.py; edit spectrum_viewer.s.\n#pragma once\n#include <cstdint>\n#include <string_view>\nnamespace png2amiga::retro {\ninline constexpr std::uint8_t spectrum_stub[] = {\n'
for i in range(0,len(data),16): text+='    '+','.join(f'0x{x:02x}' for x in data[i:i+16])+',\n'
text+='};\ninline constexpr std::string_view spectrum_assembly = R"p2a('+s+')p2a";\n}\n'
(root/'src/atari/spectrum_runtime.hpp').write_text(text)
print(f'Wrote {len(data)}-byte runtime')
