#!/usr/bin/env python3
"""Run png2amiga with given args; assert SHA-256 of output bytes matches.

Used to pin per-format output bytes before the main.cpp output-dispatch
consolidation (REFACTOR_PLAN.md Phase E). The 8+ duplicate output blocks
in main.cpp each have subtle quirks (HAM cheader is_ham=true, EHB CMAP
filtering, sliced PCHG, strips MOVE table per row); golden hashes
catch any byte-level drift introduced when collapsing those blocks
into a single helper.

Usage:
    check_output_hash.py --cli ./png2amiga --in src.png --out /tmp/x.iff \
        --sha256 abc...123 -- --mode lores --depth 3

The cli runs `<cli> <forwarded args> <in> <out>` and the script hashes
<out>. Pass `--print-hash` to only print the computed digest (use for
generating baselines).
"""
from __future__ import annotations

import argparse
import hashlib
import os
import subprocess
import sys
import tempfile


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cli", required=True, help="path to png2amiga binary")
    ap.add_argument("--in", dest="src", required=True, help="input image")
    ap.add_argument("--out", dest="out", required=True,
                    help="output path (extension picks the format)")
    ap.add_argument("--sha256", default="",
                    help="expected SHA-256 of the output file's bytes")
    ap.add_argument("--print-hash", action="store_true",
                    help="don't compare; just print the computed digest")
    ap.add_argument("forward", nargs=argparse.REMAINDER,
                    help="args to forward to png2amiga (after --)")
    args = ap.parse_args()

    forward = args.forward or []
    if forward and forward[0] == "--":
        forward = forward[1:]

    # Use a temp-dir so concurrent ctests don't fight over /tmp/x.iff.
    with tempfile.TemporaryDirectory() as td:
        out_path = os.path.join(td, os.path.basename(args.out))
        cmd = [args.cli, *forward, args.src, out_path]
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, check=False)
        except FileNotFoundError as e:
            print(f"FAIL — cli not found: {e}", file=sys.stderr)
            return 2
        if r.returncode != 0:
            print(f"FAIL — png2amiga exited {r.returncode}", file=sys.stderr)
            print(r.stderr, file=sys.stderr)
            return 1
        if not os.path.exists(out_path):
            print(f"FAIL — output file not produced: {out_path}",
                  file=sys.stderr)
            return 1
        with open(out_path, "rb") as f:
            data = f.read()
        # .h / .cpp / .c viewers embed "Generated by png2amiga X.Y.Z.NNN"
        # in a leading // comment block. The build number changes on every
        # commit, breaking byte-equality on otherwise-stable encoder output.
        # Strip leading-comment lines (until first non-comment line) before
        # hashing so the hash captures the encoded data, not the timestamp.
        ext = os.path.splitext(out_path)[1].lower()
        if ext in (".h", ".cpp", ".c"):
            lines = data.split(b"\n")
            i = 0
            while i < len(lines):
                stripped = lines[i].lstrip()
                if stripped.startswith(b"//") or stripped == b"":
                    i += 1
                    continue
                break
            data = b"\n".join(lines[i:])
        digest = hashlib.sha256(data).hexdigest()

    if args.print_hash:
        print(digest)
        return 0

    if not args.sha256:
        print("FAIL — --sha256 required (or pass --print-hash to capture)",
              file=sys.stderr)
        return 2
    if digest != args.sha256:
        print(f"FAIL — hash mismatch", file=sys.stderr)
        print(f"  expected: {args.sha256}", file=sys.stderr)
        print(f"  got:      {digest}",       file=sys.stderr)
        print(f"  cmd:      {' '.join(cmd)}", file=sys.stderr)
        return 1
    print(f"PASS — {digest}  ({os.path.basename(args.out)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
