#include "cheader_genesis.hpp"

#include <format>
#include <sstream>

namespace png2amiga::cheader_genesis {

namespace {

// Group `vals` into rows of `cols` items, each formatted via `fmt_one`.
template <typename T, typename Fn>
void emit_array_rows(std::ostringstream& os,
                     std::span<const T> vals, std::size_t cols, Fn fmt_one) {
    for (std::size_t i = 0; i < vals.size(); ++i) {
        if (i % cols == 0) os << "    ";
        fmt_one(os, vals[i]);
        if (i + 1 < vals.size()) os << ", ";
        if ((i + 1) % cols == 0 || i + 1 == vals.size()) os << '\n';
    }
}

} // namespace

Result<std::vector<std::uint8_t>> generate(const GenesisHeaderOptions& opts) {
    if (opts.tile_bytes.size() % 32 != 0) {
        return std::unexpected{Error{
            ErrorCode::invalid_dimensions,
            "Genesis cheader: tile_bytes size must be a multiple of 32"}};
    }
    if (opts.palette.size() != 64) {
        return std::unexpected{Error{
            ErrorCode::invalid_dimensions,
            "Genesis cheader: palette must be 64 entries"}};
    }
    auto cols = opts.width_pixels / 8;
    auto rows = opts.height_pixels / 8;
    if (opts.tilemap.size() != cols * rows) {
        return std::unexpected{Error{
            ErrorCode::invalid_dimensions,
            "Genesis cheader: tilemap size doesn't match width × height"}};
    }

    auto num_tiles = opts.tile_bytes.size() / 32;
    auto sym = opts.symbol.empty() ? std::string{"image"} : opts.symbol;

    // Pack tile bytes into u32 big-endian words (SGDK convention — VRAM
    // tile rows are emitted as 32-bit constants in hex). 32 bytes per
    // tile = 8 u32s per tile.
    std::vector<std::uint32_t> tile_words(num_tiles * 8);
    for (std::size_t t = 0; t < num_tiles; ++t) {
        for (std::size_t row = 0; row < 8; ++row) {
            std::uint32_t w =
                (static_cast<std::uint32_t>(opts.tile_bytes[t * 32 + row * 4 + 0]) << 24) |
                (static_cast<std::uint32_t>(opts.tile_bytes[t * 32 + row * 4 + 1]) << 16) |
                (static_cast<std::uint32_t>(opts.tile_bytes[t * 32 + row * 4 + 2]) <<  8) |
                (static_cast<std::uint32_t>(opts.tile_bytes[t * 32 + row * 4 + 3])      );
            tile_words[t * 8 + row] = w;
        }
    }

    std::ostringstream os;
    os << "// Generated by png2amiga — SGDK-compatible C header.\n";
    os << "// Mode: Sega Genesis / Mega Drive (8x8 4bpp tiles + CRAM).\n";
    os << "// Image: " << opts.width_pixels << " x " << opts.height_pixels
       << " pixels = " << cols << " x " << rows << " cells, "
       << num_tiles << " unique tiles.\n";
    os << "//\n";
    os << "// Usage:\n";
    os << "//   #include \"" << sym << ".h\"\n";
    os << "//   VDP_loadTileSet(&" << sym << "_tileset, TILE_USERINDEX, DMA);\n";
    os << "//   VDP_setMapEx(BG_A, &" << sym << "_map, TILE_ATTR_FULL("
       << "PAL0, FALSE, FALSE, FALSE, TILE_USERINDEX), 0, 0, 0, 0, "
       << cols << ", " << rows << ");\n";
    os << "//   VDP_setPaletteColors(0, " << sym << "_palette, 64);\n";
    os << "\n";
    os << "#ifndef " << sym << "_H\n";
    os << "#define " << sym << "_H\n";
    os << "\n";
    os << "#include <genesis.h>\n";
    os << "\n";

    os << "static const u32 " << sym << "_tiles["
       << tile_words.size() << "] = {\n";
    emit_array_rows<std::uint32_t>(
        os, tile_words, /*cols=*/4,
        [](std::ostringstream& s, std::uint32_t v) {
            s << std::format("0x{:08X}", v);
        });
    os << "};\n\n";

    os << "static const u16 " << sym << "_tilemap["
       << opts.tilemap.size() << "] = {\n";
    emit_array_rows<std::uint16_t>(
        os, opts.tilemap, /*cols=*/8,
        [](std::ostringstream& s, std::uint16_t v) {
            s << std::format("0x{:04X}", v);
        });
    os << "};\n\n";

    os << "static const u16 " << sym << "_palette[64] = {\n";
    emit_array_rows<std::uint16_t>(
        os, opts.palette, /*cols=*/8,
        [](std::ostringstream& s, std::uint16_t v) {
            s << std::format("0x{:04X}", v);
        });
    os << "};\n\n";

    // SGDK wrapper structs. compression=0 (raw), so no Aplib/etc. needed.
    os << "static const TileSet " << sym << "_tileset = {\n"
       << "    .compression = 0,\n"
       << "    .numTile = " << num_tiles << ",\n"
       << "    .tiles = (u32*) " << sym << "_tiles\n"
       << "};\n\n";

    os << "static const TileMap " << sym << "_map = {\n"
       << "    .compression = 0,\n"
       << "    .w = " << cols << ",\n"
       << "    .h = " << rows << ",\n"
       << "    .tilemap = (u16*) " << sym << "_tilemap\n"
       << "};\n\n";

    os << "static const Palette " << sym << "_pal = {\n"
       << "    .length = 64,\n"
       << "    .data = (u16*) " << sym << "_palette\n"
       << "};\n\n";

    os << "#endif // " << sym << "_H\n";

    auto str = os.str();
    return std::vector<std::uint8_t>(str.begin(), str.end());
}

} // namespace png2amiga::cheader_genesis
