#include "cheader.hpp"
#include "color_space.hpp"
#include "iff.hpp"
#include "palette.hpp"

#include <algorithm>
#include <cctype>
#include <cmath>
#include <cstdint>
#include <format>
#include <fstream>
#include <string>
#include <vector>

namespace png2amiga::cheader {

namespace {

// Convert a symbol name to uppercase for #define guards and macros
std::string to_upper(std::string_view s) {
    std::string result;
    result.reserve(s.size());
    for (auto c : s) {
        result.push_back(static_cast<char>(std::toupper(static_cast<unsigned char>(c))));
    }
    return result;
}

// Sanitize a symbol name: replace non-alphanumeric with underscore
std::string sanitize_symbol(std::string_view name) {
    std::string result;
    result.reserve(name.size());
    for (auto c : name) {
        if (std::isalnum(static_cast<unsigned char>(c)) || c == '_') {
            result.push_back(c);
        } else {
            result.push_back('_');
        }
    }
    // Ensure it doesn't start with a digit
    if (!result.empty() && std::isdigit(static_cast<unsigned char>(result[0]))) {
        result.insert(result.begin(), '_');
    }
    return result;
}

// CAMG viewport mode word
std::uint32_t make_camg(amiga::Mode mode, bool hires, bool interlace) {
    std::uint32_t camg = 0;
    auto params = amiga::get_mode_params(mode);
    if (hires)           camg |= 0x8000;
    if (params.is_ham)   camg |= 0x0800;
    if (params.is_ehb)   camg |= 0x0080;
    if (interlace)       camg |= 0x0004;
    return camg;
}

} // namespace

// ---------------------------------------------------------------------------
// Generate C header content
// ---------------------------------------------------------------------------

Result<std::string> generate(const bitplane::BitplaneData& planes,
                             std::span<const Color3f> palette,
                             amiga::Mode mode,
                             const CHeaderOptions& options) {
    auto sym = sanitize_symbol(options.symbol_name);
    auto SYM = to_upper(sym);

    std::string out;
    out.reserve(planes.total_bytes() * 8);  // rough estimate

    // Header guard
    out += std::format("#ifndef {}_H\n", SYM);
    out += std::format("#define {}_H\n\n", SYM);

    // Type include for UWORD
    out += "/* Generated by png2amiga — do not edit */\n\n";
    out += "#ifndef UWORD\n";
    out += "#define UWORD unsigned short\n";
    out += "#endif\n";
    out += "#ifndef ULONG\n";
    out += "#define ULONG unsigned long\n";
    out += "#endif\n\n";

    // Metadata defines
    auto camg = make_camg(mode, options.hires, options.interlace);
    out += std::format("#define {}_WIDTH   {}\n", SYM, planes.width);
    out += std::format("#define {}_HEIGHT  {}\n", SYM, planes.height);
    out += std::format("#define {}_DEPTH   {}\n", SYM, planes.depth);
    out += std::format("#define {}_BPR     {}    /* bytes per row per plane */\n",
                       SYM, planes.bytes_per_row);
    out += std::format("#define {}_CAMG    0x{:04X}\n\n", SYM, camg);

    auto words_per_row = planes.bytes_per_row / 2;

    if (options.interleaved) {
        // Single interleaved array: all planes for row 0, then row 1, etc.
        out += std::format("const UWORD {}_planes[] = {{\n", sym);

        auto words_per_interleaved_row = words_per_row * planes.depth;
        auto total_words = words_per_interleaved_row * planes.height;
        std::size_t word_count = 0;

        for (std::size_t y = 0; y < planes.height; ++y) {
            out += std::format("    /* row {} */\n", y);
            for (std::size_t p = 0; p < planes.depth; ++p) {
                out += "    ";
                auto offset = planes.plane_row_offset(p, y);
                for (std::size_t w = 0; w < words_per_row; ++w) {
                    auto byte_off = offset + w * 2;
                    auto hi = static_cast<std::uint16_t>(planes.data[byte_off]);
                    auto lo = static_cast<std::uint16_t>(planes.data[byte_off + 1]);
                    auto word = static_cast<std::uint16_t>((hi << 8) | lo);
                    ++word_count;
                    out += std::format("0x{:04X}", word);
                    if (word_count < total_words) {
                        out += ",";
                    }
                }
                out += "\n";
            }
        }

        out += "};\n\n";
    } else {
        // Separate arrays per plane
        for (std::size_t p = 0; p < planes.depth; ++p) {
            out += std::format("const UWORD {}_plane{}[] = {{\n", sym, p);

            auto total_words = words_per_row * planes.height;
            std::size_t word_count = 0;

            for (std::size_t y = 0; y < planes.height; ++y) {
                out += "    ";
                auto offset = planes.plane_row_offset(p, y);
                for (std::size_t w = 0; w < words_per_row; ++w) {
                    auto byte_off = offset + w * 2;
                    auto hi = static_cast<std::uint16_t>(planes.data[byte_off]);
                    auto lo = static_cast<std::uint16_t>(planes.data[byte_off + 1]);
                    auto word = static_cast<std::uint16_t>((hi << 8) | lo);
                    ++word_count;
                    out += std::format("0x{:04X}", word);
                    if (word_count < total_words) {
                        out += ",";
                    }
                }
                out += "\n";
            }

            out += "};\n\n";
        }
    }

    // Palette as OCS 12-bit RGB values (0x0RGB)
    // For EHB, only write 32 base colors (hardware generates the rest)
    auto pal_count = palette.size();
    if (mode == amiga::Mode::ehb && pal_count > 32) {
        pal_count = 32;
    }

    out += std::format("#define {}_COLORS  {}\n\n", SYM, pal_count);
    out += std::format("const UWORD {}_palette[] = {{\n", sym);

    for (std::size_t i = 0; i < pal_count; ++i) {
        auto rgb12 = palette::linear_to_ocs(palette[i]);
        out += std::format("    0x{:04X}", rgb12);
        if (i + 1 < pal_count) {
            out += ",";
        }
        // Add sRGB comment for readability
        auto srgb = color_space::linear_to_srgb(palette[i]).clamped();
        auto r8 = static_cast<int>(std::lround(srgb.r * 255.0f));
        auto g8 = static_cast<int>(std::lround(srgb.g * 255.0f));
        auto b8 = static_cast<int>(std::lround(srgb.b * 255.0f));
        out += std::format("  /* #{:02X}{:02X}{:02X} */", r8, g8, b8);
        out += "\n";
    }

    out += "};\n\n";

    // Copper list: per-scanline register changes
    // Format: {register_index, color_value} pairs per scanline
    if (options.copper_changes && !options.copper_changes->empty()) {
        auto& changes = *options.copper_changes;
        auto cpl = options.copper_changes_per_line;
        auto height = changes.size();

        out += std::format("#define {}_COPPER_CHANGES  {}  "
                           "/* max register changes per scanline */\n\n",
                           SYM, cpl);

        // Struct for copper change entry
        out += std::format("struct {}_copper_entry {{\n", sym);
        out += "    UWORD reg;     /* palette register index */\n";
        out += "    UWORD color;   /* OCS 12-bit 0x0RGB */\n";
        out += "};\n\n";

        // Emit as [height][changes_per_line] array
        // Unused slots filled with {0xFFFF, 0x0000} as sentinel
        out += std::format("const struct {0}_copper_entry {0}_copper"
                           "[{1}][{2}] = {{\n",
                           sym, height, cpl);

        for (std::size_t y = 0; y < height; ++y) {
            out += "    { ";
            auto& line = changes[y];
            for (std::size_t s = 0; s < cpl; ++s) {
                if (s < line.size()) {
                    auto rgb12 = palette::linear_to_ocs(line[s].color);
                    out += std::format("{{{},"
                                       "0x{:04X}}}",
                                       line[s].reg, rgb12);
                } else {
                    out += "{0xFFFF,0x0000}";  // sentinel: no change
                }
                if (s + 1 < cpl) out += ", ";
            }
            out += " }";
            if (y + 1 < height) out += ",";
            out += "\n";
        }

        out += "};\n\n";
    }

    out += std::format("#endif /* {}_H */\n", SYM);

    return out;
}

// ---------------------------------------------------------------------------
// Save C header to file
// ---------------------------------------------------------------------------

Result<void> save(std::string_view path,
                  const bitplane::BitplaneData& planes,
                  std::span<const Color3f> palette,
                  amiga::Mode mode,
                  const CHeaderOptions& options) {
    auto content = generate(planes, palette, mode, options);
    if (!content) return std::unexpected{content.error()};

    auto path_str = std::string(path);
    std::ofstream file(path_str);
    if (!file) {
        return std::unexpected{Error{
            ErrorCode::write_failed,
            "Failed to open file for writing: " + path_str,
        }};
    }

    file << *content;
    if (!file) {
        return std::unexpected{Error{
            ErrorCode::write_failed,
            "Failed to write C header to: " + path_str,
        }};
    }

    return {};
}

// ===========================================================================
// Standalone AmigaOS viewer .cpp generator
//
// Produces a single self-contained C++ file with inline image data,
// palette, copper list, and a main() that takes over the system,
// sets up the display, and waits for left mouse button.
//
// Compatible with vscode-amiga-debug toolchain (m68k-amiga-elf-gcc 14).
// ===========================================================================

Result<std::string> generate_viewer(const bitplane::BitplaneData& planes,
                                    std::span<const Color3f> palette,
                                    amiga::Mode mode,
                                    const CHeaderOptions& options) {
    auto sym = sanitize_symbol(options.symbol_name);
    auto params = amiga::get_mode_params(mode);
    auto width = planes.width;
    auto height = planes.height;
    auto depth = planes.depth;
    auto bpr = planes.bytes_per_row;
    auto is_ham = params.is_ham;

    bool is_hires = options.hires;
    auto camg = make_camg(mode, is_hires, options.interlace);

    // Palette count (EHB: only 32 base colors)
    auto pal_count = palette.size();
    if (mode == amiga::Mode::ehb && pal_count > 32) pal_count = 32;

    std::string out;
    out.reserve(planes.total_bytes() * 8 + 8192);

    // Header
    out += "// Generated by png2amiga — AmigaOS viewer\n";
    out += "// Compile: m68k-amiga-elf-gcc -m68000 -Ofast -nostdlib -o out.elf "
           "this.cpp support/gcc8_a_support.s support/gcc8_c_support.c\n";
    out += "//          elf2hunk out.elf out.exe\n\n";

    out += "#include \"support/gcc8_c_support.h\"\n";
    out += "#include <proto/exec.h>\n";
    out += "#include <proto/dos.h>\n";
    out += "#include <proto/graphics.h>\n";
    out += "#include <exec/execbase.h>\n";
    out += "#include <graphics/gfxbase.h>\n";
    out += "#include <graphics/view.h>\n";
    out += "#include <hardware/custom.h>\n";
    out += "#include <hardware/dmabits.h>\n\n";

    // System globals
    out += "struct ExecBase *SysBase;\n";
    out += "volatile struct Custom *custom;\n";
    out += "struct GfxBase *GfxBase;\n\n";

    // System backup/restore
    out += "static UWORD SystemInts, SystemDMA, SystemADKCON;\n";
    out += "static volatile APTR VBR = 0;\n";
    out += "static APTR SystemIrq;\n";
    out += "struct View *ActiView;\n\n";

    out += "static __attribute__((interrupt)) void SupervisorGetVBR() {\n";
    out += "    __asm__ volatile(\".short 0x4e7a, 0x0801\");\n";
    out += "}\n\n";

    out += "static APTR GetVBR() {\n";
    out += "    APTR vbr = 0;\n";
    out += "    if (SysBase->AttnFlags & AFF_68010)\n";
    out += "        vbr = (APTR)Supervisor((ULONG (*)())SupervisorGetVBR);\n";
    out += "    return vbr;\n";
    out += "}\n\n";

    out += "void WaitVbl() {\n";
    out += "    while ((*(volatile ULONG*)0xDFF004 & 0x1ff00) != (311<<8)) {}\n";
    out += "    while ((*(volatile ULONG*)0xDFF004 & 0x1ff00) == (311<<8)) {}\n";
    out += "}\n\n";

    out += "__attribute__((always_inline)) inline short MouseLeft() {\n";
    out += "    return !((*(volatile UBYTE*)0xbfe001) & 64);\n";
    out += "}\n\n";

    out += "void TakeSystem() {\n";
    out += "    Forbid();\n";
    out += "    SystemADKCON = custom->adkconr;\n";
    out += "    SystemInts = custom->intenar;\n";
    out += "    SystemDMA = custom->dmaconr;\n";
    out += "    ActiView = GfxBase->ActiView;\n";
    out += "    LoadView(0); WaitTOF(); WaitTOF();\n";
    out += "    WaitVbl(); WaitVbl();\n";
    out += "    OwnBlitter();\n";
    out += "    while (*(volatile UWORD*)&custom->dmaconr & (1<<14)) {}\n";
    out += "    Disable();\n";
    out += "    custom->intena = 0x7fff;\n";
    out += "    custom->intreq = 0x7fff;\n";
    out += "    custom->dmacon = 0x7fff;\n";
    out += "    for (int a = 0; a < 32; a++) custom->color[a] = 0;\n";
    out += "    WaitVbl(); WaitVbl();\n";
    out += "    VBR = GetVBR();\n";
    out += "    SystemIrq = *(volatile APTR*)(((UBYTE*)VBR) + 0x6c);\n";
    out += "}\n\n";

    out += "void FreeSystem() {\n";
    out += "    WaitVbl();\n";
    out += "    while (*(volatile UWORD*)&custom->dmaconr & (1<<14)) {}\n";
    out += "    custom->intena = 0x7fff;\n";
    out += "    custom->intreq = 0x7fff;\n";
    out += "    custom->dmacon = 0x7fff;\n";
    out += "    *(volatile APTR*)(((UBYTE*)VBR) + 0x6c) = SystemIrq;\n";
    out += "    custom->cop1lc = (ULONG)GfxBase->copinit;\n";
    out += "    custom->cop2lc = (ULONG)GfxBase->LOFlist;\n";
    out += "    custom->copjmp1 = 0x7fff;\n";
    out += "    custom->intena = SystemInts | 0x8000;\n";
    out += "    custom->dmacon = SystemDMA | 0x8000;\n";
    out += "    custom->adkcon = SystemADKCON | 0x8000;\n";
    out += "    while (*(volatile UWORD*)&custom->dmaconr & (1<<14)) {}\n";
    out += "    DisownBlitter();\n";
    out += "    Enable();\n";
    out += "    LoadView(ActiView); WaitTOF(); WaitTOF();\n";
    out += "    Permit();\n";
    out += "}\n\n";

    // FMODE=3 needed for sufficient DMA bandwidth:
    // - Hires >4 planes (always)
    // - Lores >6 planes + copper (determined later, but planar layout needed for both)
    bool use_planar = (is_hires && depth > 4) || (depth > 6);

    // --- Image data ---
    out += std::format("// {}x{}, {} bitplanes, CAMG 0x{:04X}\n",
                       width, height, depth, camg);
    // Align to 8 bytes for FMODE=3 (64-bit DMA fetch)
    auto align = use_planar ? 8 : 2;
    out += std::format("static const UWORD {}_planes[]"
                       " __attribute__((aligned({})))"
                       " __attribute__((section(\".MEMF_CHIP\"))) = {{\n",
                       sym, align);

    auto words_per_row = bpr / 2;
    auto total_words = words_per_row * depth * height;
    std::size_t word_count = 0;

    // For depth > 6 (FMODE=3): use planar layout (all rows of plane 0, then plane 1, ...)
    // This avoids modulo complications with 64-bit DMA overread.
    // For depth <= 6: use interleaved layout (plane 0 row 0, plane 1 row 0, ...).
    bool planar_layout = use_planar;

    if (planar_layout) {
        for (std::size_t p = 0; p < depth; ++p) {
            out += std::format("    /* plane {} */\n", p);
            for (std::size_t y = 0; y < height; ++y) {
                out += "    ";
                auto offset = planes.plane_row_offset(p, y);
                for (std::size_t w = 0; w < words_per_row; ++w) {
                    auto byte_off = offset + w * 2;
                    auto hi = static_cast<std::uint16_t>(planes.data[byte_off]);
                    auto lo = static_cast<std::uint16_t>(planes.data[byte_off + 1]);
                    auto word = static_cast<std::uint16_t>((hi << 8) | lo);
                    ++word_count;
                    out += std::format("0x{:04X}", word);
                    if (word_count < total_words) out += ",";
                }
                out += "\n";
            }
        }
    } else {
        for (std::size_t y = 0; y < height; ++y) {
            for (std::size_t p = 0; p < depth; ++p) {
                out += "    ";
                auto offset = planes.plane_row_offset(p, y);
                for (std::size_t w = 0; w < words_per_row; ++w) {
                    auto byte_off = offset + w * 2;
                    auto hi = static_cast<std::uint16_t>(planes.data[byte_off]);
                    auto lo = static_cast<std::uint16_t>(planes.data[byte_off + 1]);
                    auto word = static_cast<std::uint16_t>((hi << 8) | lo);
                    ++word_count;
                    out += std::format("0x{:04X}", word);
                    if (word_count < total_words) out += ",";
                }
                out += "\n";
            }
        }
    }
    out += "};\n\n";

    // --- Palette ---
    out += std::format("static const UWORD {}_palette[] = {{\n", sym);
    for (std::size_t i = 0; i < pal_count; ++i) {
        auto rgb12 = palette::linear_to_ocs(palette[i]);
        out += std::format("    0x{:04X}", rgb12);
        if (i + 1 < pal_count) out += ",";
        out += "\n";
    }
    out += "};\n\n";

    // --- Copper list (if present) ---
    bool has_copper = options.copper_changes && !options.copper_changes->empty();
    if (has_copper) {
        auto& changes = *options.copper_changes;
        auto cpl = options.copper_changes_per_line;
        auto ch_height = changes.size();

        out += std::format("// Copper: {} changes/line, {} scanlines\n",
                           cpl, ch_height);
        out += "struct CopperEntry { UWORD reg; UWORD color; };\n";
        out += std::format("static const struct CopperEntry {}_copper"
                           "[{}][{}] = {{\n", sym, ch_height, cpl);
        for (std::size_t y = 0; y < ch_height; ++y) {
            out += "    { ";
            auto& line = changes[y];
            for (std::size_t s = 0; s < cpl; ++s) {
                if (s < line.size()) {
                    auto rgb12 = palette::linear_to_ocs(line[s].color);
                    out += std::format("{{{},0x{:04X}}}", line[s].reg, rgb12);
                } else {
                    out += "{0xFFFF,0x0000}";
                }
                if (s + 1 < cpl) out += ",";
            }
            out += " }";
            if (y + 1 < ch_height) out += ",";
            out += "\n";
        }
        out += "};\n\n";
    }

    // --- Copper list builder helpers ---
    // Hardcode BPLxPTH/BPLxPTL register offsets to avoid compiler issues
    // BPL1PTH = $DFF0E0, each pair is 4 bytes apart
    out += "static inline USHORT* copSetPlanes(USHORT* cl, "
           "const UBYTE** planes, int n) {\n";
    out += "    for (int i = 0; i < n; i++) {\n";
    out += "        ULONG a = (ULONG)planes[i];\n";
    out += "        UWORD reg = 0x00E0 + i * 4;  // BPLxPTH\n";
    out += "        *cl++ = reg;\n";
    out += "        *cl++ = (UWORD)(a >> 16);\n";
    out += "        *cl++ = reg + 2;  // BPLxPTL\n";
    out += "        *cl++ = (UWORD)a;\n";
    out += "    }\n";
    out += "    return cl;\n";
    out += "}\n\n";

    // --- main() ---
    out += "int main() {\n";
    out += "    SysBase = *((struct ExecBase**)4UL);\n";
    out += "    custom = (struct Custom*)0xdff000;\n";
    out += "    GfxBase = (struct GfxBase*)OpenLibrary("
           "(CONST_STRPTR)\"graphics.library\", 0);\n";
    out += "    if (!GfxBase) return 0;\n\n";

    // Check if AGA is required but not present
    bool requires_aga = (pal_count > 32) || (depth > 6) ||
                        (is_hires && depth > 4);
    if (requires_aga) {
        out += "    // Check for AGA: graphics.library v39+ only exists on A1200/A4000\n";
        out += "    if (GfxBase->LibNode.lib_Version < 39) {\n";
        out += "        struct Library* DOSBase = OpenLibrary("
               "(CONST_STRPTR)\"dos.library\", 0);\n";
        out += "        if (DOSBase) {\n";
        out += "            Write(Output(), (APTR)"
               "\"This image requires AGA (A1200/A4000).\\n\", 42);\n";
        out += "            Delay(150);\n";
        out += "            CloseLibrary(DOSBase);\n";
        out += "        }\n";
        out += "        CloseLibrary((struct Library*)GfxBase);\n";
        out += "        return 0;\n";
        out += "    }\n\n";
    }

    out += "    TakeSystem();\n";
    out += "    WaitVbl();\n\n";

    // Calculate copper list size: display setup + bitplane ptrs + colors + copper changes + end
    auto cop_size = 128 + depth * 4 * 2 + pal_count * 4;
    if (pal_count > 32) {
        // AGA: double writes (LOCT high + low) + BPLCON3 per bank + reset
        auto num_banks = (pal_count + 31) / 32;
        cop_size += pal_count * 4;  // double the color writes (LOCT=1 pass)
        cop_size += static_cast<std::size_t>((num_banks * 2 + 1) * 4);  // BPLCON3 switches
    }
    if (has_copper) {
        cop_size += height * options.copper_changes_per_line * 8 + height * 4;
        if (pal_count > 32) {
            // Extra space for BPLCON3 bank switches + reset per line
            cop_size += height * 8;
        }
    }
    cop_size += 128;  // padding for blank-below, 256-boundary WAITs, end markers

    out += std::format("    USHORT* copper1 = (USHORT*)AllocMem({}, MEMF_CHIP);\n",
                       cop_size);
    out += "    USHORT* cl = copper1;\n\n";

    // Display setup — use standard Amiga display parameters
    bool is_lace = options.interlace;
    auto y_start = 44;
    // For interlace: display window is per-field (half total height)
    // disp_height no longer needed — using fixed PAL diwstop (0x2CC1)

    // FMODE=3 needed when copper steals DMA cycles from 8-plane fetch
    // FMODE=3 needed when DMA bandwidth is tight:
    // - Lores >6 planes + copper
    // - Hires >4 planes (always, even without copper)
    bool need_fmode3 = ((depth > 6) && has_copper) ||
                       (is_hires && depth > 4);

    if (is_hires && need_fmode3) {
        // FMODE=3 hires: ddfstrt = normal (0x3C) - 8 = 0x34
        out += "    *cl++ = offsetof(struct Custom, ddfstrt); *cl++ = 0x0034;\n";
        out += "    *cl++ = offsetof(struct Custom, ddfstop); *cl++ = 0x00D4;\n";
    } else if (is_hires) {
        out += "    *cl++ = offsetof(struct Custom, ddfstrt); *cl++ = 0x003C;\n";
        out += "    *cl++ = offsetof(struct Custom, ddfstop); *cl++ = 0x00D4;\n";
    } else {
        // Lores: standard 0x38, or 0x30 for FMODE=3 (0x38 - 8)
        auto lores_ddfstrt = need_fmode3 ? 0x0030 : 0x0038;
        out += std::format("    *cl++ = offsetof(struct Custom, ddfstrt); *cl++ = 0x{:04X};\n",
                           lores_ddfstrt);
        out += "    *cl++ = offsetof(struct Custom, ddfstop); *cl++ = 0x00D0;\n";
    }
    out += std::format("    *cl++ = offsetof(struct Custom, diwstrt); "
                       "*cl++ = 0x{:04X};\n", 0x0081 + (y_start << 8));
    // Standard PAL diwstop — works for all heights, black below image
    out += "    *cl++ = offsetof(struct Custom, diwstop); *cl++ = 0x2CC1;\n";

    // (need_fmode3 declared earlier)
    if (use_planar) {
        out += std::format("    *cl++ = 0x01fc; *cl++ = 0x{:04X};  // FMODE\n",
                           need_fmode3 ? 0x0003 : 0x0000);
    }

    // BPLCON0
    // BPLCON0: BPU2-0 in bits 14-12, BPU3 in bit 4 (AGA 8th plane)
    auto bpu = static_cast<int>(depth) & 7;     // planes 1-7
    auto bpu3 = (depth == 8) ? (1 << 4) : 0;    // 8th plane on AGA
    auto bplcon0 = (bpu << 12) | bpu3 | (1 << 9);  // + COLOR
    if (is_ham) bplcon0 |= (1 << 11);           // HAM
    if (is_hires) bplcon0 |= (1 << 15);  // HIRES
    if (is_lace) bplcon0 |= (1 << 2);           // LACE
    // EHB: no special bit (hardware auto-detects 6 planes without HAM)

    out += std::format("    *cl++ = offsetof(struct Custom, bplcon0); "
                       "*cl++ = 0x{:04X};\n", bplcon0);
    out += "    *cl++ = offsetof(struct Custom, bplcon1); *cl++ = 0;\n";
    // KILLEHB (bit 9): prevent 6-plane non-EHB from triggering EHB
    auto bplcon2 = (depth == 6 && !params.is_ehb && !is_ham) ? 0x0200 : 0x0000;
    out += std::format("    *cl++ = offsetof(struct Custom, bplcon2); *cl++ = 0x{:04X};\n",
                       bplcon2);
    out += "    *cl++ = 0x0106; *cl++ = 0x0000;  // BPLCON3 = 0 (bank 0, no LOCT)\n\n";

    // Planar modulo: 0 normally, +bpr for interlace (skip other field), -8 for FMODE=3
    int planar_mod = (is_lace ? static_cast<int>(bpr) : 0) + (need_fmode3 ? -8 : 0);

    if (use_planar) {
        // Planar layout: each plane is contiguous.
        // Normal: mod=0. Interlace: mod=bpr (skip other field's row).
        // FMODE=3: subtract 8 from normal mod.
        auto plane_size = bpr * height;
        out += std::format("    *cl++ = offsetof(struct Custom, bpl1mod); *cl++ = {};\n",
                           planar_mod);
        out += std::format("    *cl++ = offsetof(struct Custom, bpl2mod); *cl++ = {};\n\n",
                           planar_mod);

        out += std::format("    const UBYTE* planes[{}];\n", depth);
        out += std::format("    for (int i = 0; i < {}; i++)\n", depth);
        out += std::format("        planes[i] = (const UBYTE*){}_planes + {} * i;\n",
                           sym, plane_size);
        out += std::format("    cl = copSetPlanes(cl, planes, {});\n\n", depth);
    } else {
        // Interleaved layout: planes interleaved per row
        auto mod = static_cast<int>(bpr) * (static_cast<int>(depth) - 1);
        if (is_lace) {
            mod = static_cast<int>(bpr) * (static_cast<int>(depth) * 2 - 1);
        }
        out += std::format("    *cl++ = offsetof(struct Custom, bpl1mod); "
                           "*cl++ = {};\n", mod);
        out += std::format("    *cl++ = offsetof(struct Custom, bpl2mod); "
                           "*cl++ = {};\n\n", mod);

        out += std::format("    const UBYTE* planes[{}];\n", depth);
        out += std::format("    for (int i = 0; i < {}; i++)\n", depth);
        out += std::format("        planes[i] = (const UBYTE*){}_planes + {} * i;\n",
                           sym, bpr);
        out += std::format("    cl = copSetPlanes(cl, planes, {});\n\n", depth);
    }

    // Set palette via copper list.
    // AGA >32 colors: BPLCON3 bank switching.
    // For HAM modes: skip LOCT write — the nibble-copy (0xN → 0xNN)
    //   matches what the encoder computes (palette::quantize_to_ocs).
    // For standard modes: LOCT double-write zeroes low nibbles to prevent
    //   the auto-copy artifact that makes bright colors overshoot.
    if (pal_count > 32) {
        auto num_banks = (pal_count + 31) / 32;
        out += std::format("    // AGA palette: {} colors, {} banks\n",
                           pal_count, num_banks);
        for (std::size_t bank = 0; bank < static_cast<std::size_t>(num_banks); ++bank) {
            auto base = bank * 32;
            auto count = std::min(std::size_t{32}, pal_count - base);
            auto bank_bits = static_cast<unsigned>(bank << 13);

            // High nibbles (LOCT=0)
            out += std::format("    *cl++ = 0x0106; *cl++ = 0x{:04X};"
                               "  // bank {}\n", bank_bits, bank);
            out += std::format("    for (int i = 0; i < {}; i++) {{\n", count);
            out += "        *cl++ = offsetof(struct Custom, color) + i * 2;\n";
            out += std::format("        *cl++ = {}_palette[{} + i];\n", sym, base);
            out += "    }\n";

            // Low nibbles (LOCT=1) — only for non-HAM modes
            if (!is_ham) {
                out += std::format("    *cl++ = 0x0106; *cl++ = 0x{:04X};"
                                   "  // bank {}, LOCT=1\n",
                                   bank_bits | 0x0200, bank);
                out += std::format("    for (int i = 0; i < {}; i++) {{\n", count);
                out += "        *cl++ = offsetof(struct Custom, color) + i * 2;\n";
                out += "        *cl++ = 0x0000;\n";
                out += "    }\n";
            }
        }
        // Reset to bank 0, LOCT=0
        out += "    *cl++ = 0x0106; *cl++ = 0x0000;\n\n";
    } else {
        // OCS/ECS: just write 32 colors directly
        out += std::format("    for (int i = 0; i < {}; i++) {{\n", pal_count);
        out += "        *cl++ = offsetof(struct Custom, color) + i * 2;\n";
        out += std::format("        *cl++ = {}_palette[i];\n", sym);
        out += "    }\n\n";
    }

    // Copper changes per scanline
    if (has_copper) {
        auto cpl = options.copper_changes_per_line;
        bool aga_banks = (pal_count > 32);
        out += "    // Per-scanline copper palette changes\n";
        out += std::format("    for (int y = 0; y < {}; y++) {{\n", height);
        out += std::format("        USHORT line = y + {};\n", y_start);
        out += "        if (line == 256) {\n";
        out += "            *cl++ = 0xFFDF; *cl++ = 0xFFFE;  // cross 256 boundary\n";
        out += "        }\n";
        out += "        *cl++ = ((line & 0xFF) << 8) | 0x01;\n";
        out += "        *cl++ = 0xfffe;\n";
        if (aga_banks) {
            // AGA: changes are pre-sorted by register (bank 0 first).
            // Track current bank, switch only when crossing a bank boundary,
            // reset to bank 0 once at the end.
            out += "        int cur_bank = 0;\n";
            out += std::format("        for (int s = 0; s < {}; s++) {{\n", cpl);
            out += std::format("            UWORD reg = {}_copper[y][s].reg;\n", sym);
            out += "            if (reg == 0xFFFF) continue;\n";
            out += "            int bank = reg / 32;\n";
            out += "            if (bank != cur_bank) {\n";
            out += "                *cl++ = 0x0106;\n";
            out += "                *cl++ = (UWORD)(bank << 13);\n";
            out += "                cur_bank = bank;\n";
            out += "            }\n";
            out += "            *cl++ = offsetof(struct Custom, color)"
                   " + (reg % 32) * 2;\n";
            out += std::format("            *cl++ = {}_copper[y][s].color;\n", sym);
            out += "        }\n";
            out += "        if (cur_bank != 0) {\n";
            out += "            *cl++ = 0x0106; *cl++ = 0x0000;\n";
            out += "        }\n";
        } else {
            out += std::format("        for (int s = 0; s < {}; s++) {{\n", cpl);
            out += std::format("            UWORD reg = {}_copper[y][s].reg;\n", sym);
            out += "            if (reg == 0xFFFF) continue;\n";
            out += std::format("            *cl++ = offsetof(struct Custom, color)"
                               " + reg * 2;\n");
            out += std::format("            *cl++ = {}_copper[y][s].color;\n", sym);
            out += "        }\n";
        }
        out += "    }\n\n";
    }

    // Blank below image: disable bitplanes after last line
    {
        auto last_line = y_start + (is_lace
            ? static_cast<int>(height / 2)
            : static_cast<int>(height));
        if (last_line >= 256 && !has_copper) {
            // Need boundary cross only if per-scanline copper loop didn't already do it
            out += "    *cl++ = 0xFFDF; *cl++ = 0xFFFE;"
                   "  // WAIT past line 255\n";
        }
        out += std::format("    *cl++ = ({}<<8)|1; *cl++ = 0xfffe;"
                           "  // WAIT line {}\n",
                           last_line >= 256 ? (last_line & 0xFF) : last_line,
                           last_line);
        out += "    *cl++ = offsetof(struct Custom, bplcon0); "
               "*cl++ = 0x0200;  // 0 planes, blank\n";
    }

    // End copper list
    out += "    *cl++ = 0xffff; *cl++ = 0xfffe;\n\n";

    // For interlace: build a second copper list for the even field
    // and a vblank interrupt handler that swaps cop1lc based on LOF bit.
    if (is_lace) {
        out += std::format("    USHORT* copper2 = (USHORT*)AllocMem({}, MEMF_CHIP);\n",
                           cop_size);
        out += "    USHORT* cl2 = copper2;\n\n";

        // Rebuild even field copper list
        if (is_hires) {
            auto h_ddf = need_fmode3 ? 0x0034 : 0x003C;
            out += std::format("    *cl2++ = offsetof(struct Custom, ddfstrt); *cl2++ = 0x{:04X};\n", h_ddf);
            out += "    *cl2++ = offsetof(struct Custom, ddfstop); *cl2++ = 0x00D4;\n";
        } else {
            out += "    *cl2++ = offsetof(struct Custom, ddfstrt); *cl2++ = 0x0038;\n";
            out += "    *cl2++ = offsetof(struct Custom, ddfstop); *cl2++ = 0x00D0;\n";
        }
        out += std::format("    *cl2++ = offsetof(struct Custom, diwstrt); "
                           "*cl2++ = 0x{:04X};\n", 0x0081 + (y_start << 8));
        out += "    *cl2++ = offsetof(struct Custom, diwstop); *cl2++ = 0x2CC1;\n";
        if (use_planar)
            out += std::format("    *cl2++ = 0x01fc; *cl2++ = 0x{:04X};\n",
                               need_fmode3 ? 0x0003 : 0x0000);
        out += std::format("    *cl2++ = offsetof(struct Custom, bplcon0); "
                           "*cl2++ = 0x{:04X};\n", bplcon0);
        out += "    *cl2++ = offsetof(struct Custom, bplcon1); *cl2++ = 0;\n";
        out += std::format("    *cl2++ = offsetof(struct Custom, bplcon2); *cl2++ = 0x{:04X};\n",
                           bplcon2);

        if (use_planar) {
            // Planar interlace: mod = bpr (skip other field row), -8 for FMODE=3
            auto plane_size = bpr * height;
            out += std::format("    *cl2++ = offsetof(struct Custom, bpl1mod); *cl2++ = {};\n",
                               planar_mod);
            out += std::format("    *cl2++ = offsetof(struct Custom, bpl2mod); *cl2++ = {};\n",
                               planar_mod);
            out += std::format("    const UBYTE* planes_even[{}];\n", depth);
            out += std::format("    for (int i = 0; i < {}; i++)\n", depth);
            out += std::format("        planes_even[i] = (const UBYTE*){}_planes"
                               " + {} * i + {};\n",
                               sym, plane_size, bpr);  // offset by one row within each plane
        } else {
            // Interleaved: mod skips other field, even field starts one interleaved row later
            auto lace_mod = static_cast<int>(bpr) * (static_cast<int>(depth) * 2 - 1);
            out += std::format("    *cl2++ = offsetof(struct Custom, bpl1mod); "
                               "*cl2++ = {};\n", lace_mod);
            out += std::format("    *cl2++ = offsetof(struct Custom, bpl2mod); "
                               "*cl2++ = {};\n", lace_mod);
            out += std::format("    const UBYTE* planes_even[{}];\n", depth);
            out += std::format("    for (int i = 0; i < {}; i++)\n", depth);
            out += std::format("        planes_even[i] = (const UBYTE*){}_planes"
                               " + {} * i + {};\n",
                               sym, bpr, bpr * depth);  // one interleaved row later
        }
        out += std::format("    cl2 = copSetPlanes(cl2, planes_even, {});\n", depth);
        // Palette already set via CPU; copper just sets bank 0
        {
            auto write_count = std::min(pal_count, std::size_t{32});
            out += std::format("    for (int i = 0; i < {}; i++) {{\n", write_count);
            out += "        *cl2++ = offsetof(struct Custom, color) + i * 2;\n";
            out += std::format("        *cl2++ = {}_palette[i];\n", sym);
            out += "    }\n";
        }
        // Blank below image in even field
        {
            auto last_line = y_start + static_cast<int>(height / 2);
            if (last_line >= 256) {
                out += "    *cl2++ = 0xFFDF; *cl2++ = 0xFFFE;\n";
                out += std::format("    *cl2++ = ({}<<8)|1; *cl2++ = 0xfffe;\n",
                                   last_line & 0xFF);
            } else {
                out += std::format("    *cl2++ = ({}<<8)|1; *cl2++ = 0xfffe;\n",
                                   last_line);
            }
            out += "    *cl2++ = offsetof(struct Custom, bplcon0); "
                   "*cl2++ = 0x0200;\n";
        }
        out += "    *cl2++ = 0xffff; *cl2++ = 0xfffe;\n\n";

        // Store pointers for the interrupt handler
        out += "    // Globals for vblank interrupt field switching\n";
        out += "    static volatile ULONG cop_odd, cop_even;\n";
        out += "    cop_odd = (ULONG)copper1;\n";
        out += "    cop_even = (ULONG)copper2;\n\n";
    }

    // Turn off floppy motor
    out += "    // Turn off floppy motor\n";
    out += "    *(volatile UBYTE*)0xbfd100 |= 0xf8;  // deselect + motor off\n\n";

    // Start display
    out += "    custom->cop1lc = (ULONG)copper1;\n";
    if (is_lace) {
        out += "    custom->cop2lc = (ULONG)copper2;\n";
    }
    out += "    custom->dmacon = DMAF_BLITTER;\n";
    out += "    custom->copjmp1 = 0x7fff;\n";
    out += "    custom->dmacon = DMAF_SETCLR | DMAF_MASTER | "
           "DMAF_RASTER | DMAF_COPPER;\n\n";

    if (is_lace) {
        // Vblank interrupt handler: swap copper list based on LOF bit
        // LOF (Long Frame) is bit 15 of VPOSR (0xDFF004)
        out += "    // Install vblank interrupt for interlace field switching\n";
        out += "    *(volatile APTR*)(((UBYTE*)VBR) + 0x6c) = (APTR)+[]() __attribute__((interrupt)) {\n";
        out += "        volatile struct Custom* c = (volatile struct Custom*)0xdff000;\n";
        out += "        c->intreq = (1<<5); c->intreq = (1<<5); // ack VBL\n";
        out += "        if (*(volatile UWORD*)0xdff004 & 0x8000)  // LOF: long frame ended\n";
        out += "            c->cop1lc = cop_even;  // next frame is even (short)\n";
        out += "        else\n";
        out += "            c->cop1lc = cop_odd;   // next frame is odd (long)\n";
        out += "    };\n";
        out += "    custom->intena = 0x8000 | (1<<5);  // enable VBL interrupt\n";
        out += "    Enable();  // allow CPU to service interrupts\n\n";
    }

    // Wait for left mouse button
    out += "    while (!MouseLeft()) { WaitVbl(); }\n\n";

    // Cleanup
    if (is_lace) {
        out += "    Disable();  // re-disable before FreeSystem restores state\n";
    }
    out += "    FreeSystem();\n";
    out += std::format("    FreeMem(copper1, {});\n", cop_size);
    if (is_lace) {
        out += std::format("    FreeMem(copper2, {});\n", cop_size);
    }
    out += "    CloseLibrary((struct Library*)GfxBase);\n";
    out += "    return 0;\n";
    out += "}\n";

    return out;
}

Result<void> save_viewer(std::string_view path,
                         const bitplane::BitplaneData& planes,
                         std::span<const Color3f> palette,
                         amiga::Mode mode,
                         const CHeaderOptions& options) {
    auto content = generate_viewer(planes, palette, mode, options);
    if (!content) return std::unexpected{content.error()};

    auto path_str = std::string(path);
    std::ofstream file(path_str);
    if (!file) {
        return std::unexpected{Error{
            ErrorCode::write_failed,
            "Failed to open file for writing: " + path_str,
        }};
    }

    file << *content;
    if (!file) {
        return std::unexpected{Error{
            ErrorCode::write_failed,
            "Failed to write viewer source to: " + path_str,
        }};
    }

    return {};
}

} // namespace png2amiga::cheader
