#include "cpp_writer.hpp"

#include "palette.hpp"

#include <cctype>
#include <filesystem>
#include <fstream>
#include <format>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace png2amiga::cpp_writer {

namespace {

// Split "a::b::c" into {"a","b","c"}.
std::vector<std::string> split_namespace(std::string_view s) {
    std::vector<std::string> out;
    std::size_t i = 0;
    while (i < s.size()) {
        auto j = s.find("::", i);
        if (j == std::string_view::npos) {
            out.emplace_back(s.substr(i));
            break;
        }
        out.emplace_back(s.substr(i, j - i));
        i = j + 2;
    }
    return out;
}

std::string basename_no_ext(std::string_view path) {
    std::filesystem::path p{std::string{path}};
    return p.stem().string();
}

std::string last_namespace_segment(std::string_view ns) {
    auto i = ns.rfind("::");
    return std::string{i == std::string_view::npos ? ns : ns.substr(i + 2)};
}

// Emit open/close of nested namespaces.
void emit_ns_open(std::ostream& os, const std::vector<std::string>& parts) {
    if (parts.empty()) return;
    os << "namespace ";
    for (std::size_t i = 0; i < parts.size(); ++i) {
        if (i) os << "::";
        os << parts[i];
    }
    os << " {\n";
}

void emit_ns_close(std::ostream& os, const std::vector<std::string>& parts) {
    if (parts.empty()) return;
    os << "} // namespace ";
    for (std::size_t i = 0; i < parts.size(); ++i) {
        if (i) os << "::";
        os << parts[i];
    }
    os << "\n";
}

// Emit palette entries as C++26 std::array literal.
// OCS: std::array<std::uint16_t, N> in 0x0RGB format.
// AGA: std::array<std::uint32_t, N> in 0x00RRGGBB format.
void emit_palette(std::ostream& os, std::span<const Color3f> pal,
                  Chipset chipset) {
    if (chipset == Chipset::ocs) {
        os << "    ";
        for (std::size_t i = 0; i < pal.size(); ++i) {
            os << std::format("0x{:04X}", palette::linear_to_ocs(pal[i]));
            if (i + 1 < pal.size()) os << ", ";
            if ((i + 1) % 8 == 0 && i + 1 < pal.size()) os << "\n    ";
        }
        os << "\n";
    } else {
        os << "    ";
        for (std::size_t i = 0; i < pal.size(); ++i) {
            os << std::format("0x{:08X}", palette::linear_to_aga(pal[i]));
            if (i + 1 < pal.size()) os << ", ";
            if ((i + 1) % 4 == 0 && i + 1 < pal.size()) os << "\n    ";
        }
        os << "\n";
    }
}

// Emit bitplane bytes as a std::array<std::uint16_t, N> literal
// (words are built big-endian, matching 68k native order).
void emit_bitplane_words(std::ostream& os,
                         std::span<const std::uint8_t> bytes) {
    auto nwords = bytes.size() / 2;
    constexpr std::size_t per_line = 12;
    for (std::size_t i = 0; i < nwords; ++i) {
        if (i % per_line == 0) os << "    ";
        auto hi = bytes[i * 2];
        auto lo = bytes[i * 2 + 1];
        std::uint16_t w = static_cast<std::uint16_t>((hi << 8) | lo);
        os << std::format("0x{:04X}", w);
        if (i + 1 < nwords) os << ",";
        if ((i + 1) % per_line == 0 || i + 1 == nwords) os << "\n";
        else os << " ";
    }
}

// Emit the tilemap as std::array<MapCell, N>. Raw u16 initializers.
void emit_tilemap(std::ostream& os, std::span<const tile_pack::MapCell> cells,
                  std::size_t per_row) {
    for (std::size_t i = 0; i < cells.size(); ++i) {
        if (i % per_row == 0) os << "    ";
        os << std::format("MapCell{{0x{:04X}}}", cells[i].raw);
        if (i + 1 < cells.size()) os << ",";
        if ((i + 1) % per_row == 0 || i + 1 == cells.size()) os << "\n";
        else os << " ";
    }
}

} // namespace

Result<void> write_tile_pack(std::string_view base_path,
                             const tile_pack::PackResult& pack,
                             const Options& opts) {
    auto ns_parts = split_namespace(opts.namespace_name);
    auto short_name = last_namespace_segment(opts.namespace_name);
    auto stem = basename_no_ext(base_path);
    auto hpp_path = std::string{base_path} + ".hpp";
    auto cpp_path = std::string{base_path} + ".cpp";

    auto pal_words = pack.planes.total_bytes() / 2;
    auto tile_words = pack.tile_bytes / 2;
    auto pal_elem_type = (opts.chipset == Chipset::ocs)
        ? std::string_view{"std::uint16_t"}
        : std::string_view{"std::uint32_t"};
    (void)pal_words; (void)tile_words;

    // -------------------- header --------------------
    {
        std::ofstream hpp{hpp_path};
        if (!hpp) {
            return std::unexpected{Error{ErrorCode::write_failed,
                std::format("cannot open {}", hpp_path)}};
        }
        hpp << "// Generated by png2amiga-assets — do not edit.\n";
        hpp << "// Source tilesheet: " << stem << "\n";
        hpp << "#pragma once\n\n";
        hpp << "#include <array>\n";
        hpp << "#include <cstdint>\n\n";

        emit_ns_open(hpp, ns_parts);
        hpp << "\n";

        // Metadata constants
        hpp << std::format("inline constexpr unsigned tile_w         = {};\n", pack.planes.width);
        hpp << std::format("inline constexpr unsigned tile_h         = {};\n",
            pack.num_unique_tiles > 0 ? pack.planes.height / pack.num_unique_tiles : 0);
        hpp << std::format("inline constexpr unsigned depth          = {};\n", pack.planes.depth);
        hpp << std::format("inline constexpr unsigned bytes_per_row  = {};\n", pack.bytes_per_row);
        hpp << std::format("inline constexpr unsigned tile_bytes     = {};\n", pack.tile_bytes);
        hpp << std::format("inline constexpr unsigned num_tiles      = {};\n", pack.num_unique_tiles);
        hpp << std::format("inline constexpr unsigned map_w          = {};\n", pack.map_w);
        hpp << std::format("inline constexpr unsigned map_h          = {};\n", pack.map_h);
        hpp << std::format("inline constexpr unsigned num_cells      = {};\n", pack.num_cells);
        hpp << std::format("inline constexpr unsigned palette_size   = {};\n", pack.palette.size());
        hpp << "\n";

        // Tilemap cell type
        hpp <<
            "struct MapCell {\n"
            "    std::uint16_t raw;\n"
            "    [[nodiscard]] constexpr std::uint16_t index() const noexcept {\n"
            "        return static_cast<std::uint16_t>(raw & 0x3FFFu);\n"
            "    }\n"
            "    [[nodiscard]] constexpr bool h_flip() const noexcept {\n"
            "        return (raw & 0x8000u) != 0;\n"
            "    }\n"
            "    [[nodiscard]] constexpr bool v_flip() const noexcept {\n"
            "        return (raw & 0x4000u) != 0;\n"
            "    }\n"
            "};\n"
            "static_assert(sizeof(MapCell) == 2);\n\n";

        // Declarations
        hpp << std::format(
            "extern const std::array<std::uint16_t, num_tiles * (tile_bytes / 2)> tiles_data;\n"
            "extern const std::array<MapCell, num_cells> tilemap;\n"
            "extern const std::array<{}, palette_size> palette;\n\n",
            pal_elem_type);

        // Convenience helpers
        hpp <<
            "[[nodiscard]] constexpr const std::uint16_t* tile_ptr(std::uint16_t idx) noexcept {\n"
            "    return tiles_data.data() + static_cast<std::size_t>(idx) * (tile_bytes / 2);\n"
            "}\n\n";
        hpp << std::format(
            "[[nodiscard]] constexpr MapCell cell_at(unsigned x, unsigned y) noexcept {{\n"
            "    return tilemap[y * map_w + x];\n"
            "}}\n\n");

        emit_ns_close(hpp, ns_parts);
        (void)short_name;
    }

    // -------------------- source --------------------
    {
        std::ofstream cpp{cpp_path};
        if (!cpp) {
            return std::unexpected{Error{ErrorCode::write_failed,
                std::format("cannot open {}", cpp_path)}};
        }
        cpp << "// Generated by png2amiga-assets — do not edit.\n";
        cpp << "#include \"" << std::filesystem::path{hpp_path}.filename().string() << "\"\n";
        if (opts.chip_attr == "PA_ASSET_CHIP") {
            cpp << "#include \"pa/chip_attr.hpp\"\n";
        }
        cpp << "\n";

        emit_ns_open(cpp, ns_parts);
        cpp << "\n";

        // tiles_data
        if (!opts.chip_attr.empty()) cpp << opts.chip_attr << "\n";
        cpp << "const std::array<std::uint16_t, num_tiles * (tile_bytes / 2)> tiles_data = {\n";
        emit_bitplane_words(cpp, pack.planes.data);
        cpp << "};\n\n";

        // tilemap
        cpp << "const std::array<MapCell, num_cells> tilemap = {\n";
        emit_tilemap(cpp, pack.tilemap, pack.map_w);
        cpp << "};\n\n";

        // palette
        cpp << std::format("const std::array<{}, palette_size> palette = {{\n", pal_elem_type);
        emit_palette(cpp, pack.palette, opts.chipset);
        cpp << "};\n\n";

        emit_ns_close(cpp, ns_parts);
    }

    return {};
}

Result<void> write_strip_pack(std::string_view base_path,
                              const strip_pack::PackResult& pack,
                              const Options& opts) {
    auto ns_parts = split_namespace(opts.namespace_name);
    auto stem = basename_no_ext(base_path);
    auto hpp_path = std::string{base_path} + ".hpp";
    auto cpp_path = std::string{base_path} + ".cpp";

    auto pal_elem_type = (opts.chipset == Chipset::ocs)
        ? std::string_view{"std::uint16_t"}
        : std::string_view{"std::uint32_t"};

    // -------------------- header --------------------
    {
        std::ofstream hpp{hpp_path};
        if (!hpp) {
            return std::unexpected{Error{ErrorCode::write_failed,
                std::format("cannot open {}", hpp_path)}};
        }
        hpp << "// Generated by png2amiga-assets — do not edit.\n";
        hpp << "// Source strip: " << stem << "\n";
        hpp << "#pragma once\n\n";
        hpp << "#include <array>\n";
        hpp << "#include <cstdint>\n\n";

        emit_ns_open(hpp, ns_parts);
        hpp << "\n";

        hpp << std::format("inline constexpr unsigned frame_w         = {};\n", pack.frame_w);
        hpp << std::format("inline constexpr unsigned frame_h         = {};\n", pack.frame_h);
        hpp << std::format("inline constexpr unsigned storage_w       = {};\n", pack.storage_w);
        hpp << std::format("inline constexpr unsigned depth           = {};\n", pack.planes.depth);
        hpp << std::format("inline constexpr unsigned bytes_per_row   = {};\n", pack.bytes_per_row);
        hpp << std::format("inline constexpr unsigned frame_bytes     = {};\n", pack.frame_bytes);
        hpp << std::format("inline constexpr unsigned num_frames      = {};\n", pack.num_frames);
        hpp << std::format("inline constexpr unsigned preshift        = {};\n", pack.preshift);
        hpp << std::format("inline constexpr unsigned palette_size    = {};\n", pack.palette.size());
        hpp << std::format("inline constexpr bool     has_mask        = {};\n",
                           pack.has_mask ? "true" : "false");
        if (pack.has_mask) {
            hpp << std::format("inline constexpr unsigned mask_bytes      = {};\n", pack.mask_bytes);
        }
        hpp << "\n";

        hpp << std::format(
            "extern const std::array<std::uint16_t, num_frames * preshift * (frame_bytes / 2)> frames_data;\n");
        if (pack.has_mask) {
            hpp << std::format(
                "extern const std::array<std::uint16_t, num_frames * preshift * (mask_bytes / 2)> mask_data;\n");
        }
        hpp << std::format(
            "extern const std::array<{}, palette_size> palette;\n\n", pal_elem_type);

        hpp <<
            "// Returns the bitplane data for frame n with horizontal sub-word\n"
            "// shift k in [0, preshift). For preshift==1, k is ignored.\n"
            "[[nodiscard]] constexpr const std::uint16_t* frame_ptr(unsigned n, unsigned k = 0) noexcept {\n"
            "    return frames_data.data() + (static_cast<std::size_t>(n) * preshift + k) * (frame_bytes / 2);\n"
            "}\n";
        if (pack.has_mask) {
            hpp <<
                "[[nodiscard]] constexpr const std::uint16_t* mask_ptr(unsigned n, unsigned k = 0) noexcept {\n"
                "    return mask_data.data() + (static_cast<std::size_t>(n) * preshift + k) * (mask_bytes / 2);\n"
                "}\n";
        }
        hpp <<
            "// Select the pre-shifted copy for a target X coordinate.\n"
            "// Engine usage: auto* p = frame_ptr(f, shift_for_x(target_x));\n"
            "[[nodiscard]] constexpr unsigned shift_for_x(unsigned x) noexcept {\n"
            "    return preshift <= 1 ? 0u : (x & 15u) / (16u / preshift);\n"
            "}\n\n";

        emit_ns_close(hpp, ns_parts);
    }

    // -------------------- source --------------------
    {
        std::ofstream cpp{cpp_path};
        if (!cpp) {
            return std::unexpected{Error{ErrorCode::write_failed,
                std::format("cannot open {}", cpp_path)}};
        }
        cpp << "// Generated by png2amiga-assets — do not edit.\n";
        cpp << "#include \"" << std::filesystem::path{hpp_path}.filename().string() << "\"\n";
        if (opts.chip_attr == "PA_ASSET_CHIP") {
            cpp << "#include \"pa/chip_attr.hpp\"\n";
        }
        cpp << "\n";

        emit_ns_open(cpp, ns_parts);
        cpp << "\n";

        if (!opts.chip_attr.empty()) cpp << opts.chip_attr << "\n";
        cpp << "const std::array<std::uint16_t, num_frames * preshift * (frame_bytes / 2)> frames_data = {\n";
        emit_bitplane_words(cpp, pack.planes.data);
        cpp << "};\n\n";

        if (pack.has_mask) {
            if (!opts.chip_attr.empty()) cpp << opts.chip_attr << "\n";
            cpp << "const std::array<std::uint16_t, num_frames * preshift * (mask_bytes / 2)> mask_data = {\n";
            emit_bitplane_words(cpp, pack.mask_data);
            cpp << "};\n\n";
        }

        cpp << std::format("const std::array<{}, palette_size> palette = {{\n", pal_elem_type);
        emit_palette(cpp, pack.palette, opts.chipset);
        cpp << "};\n\n";

        emit_ns_close(cpp, ns_parts);
    }

    return {};
}

Result<void> write_tile_pool(std::string_view base_path,
                             const tile_pack::TilePool& pool,
                             const Options& opts) {
    auto ns_parts = split_namespace(opts.namespace_name);
    auto stem = basename_no_ext(base_path);
    auto hpp_path = std::string{base_path} + ".hpp";
    auto cpp_path = std::string{base_path} + ".cpp";

    auto pal_elem_type = (opts.chipset == Chipset::ocs)
        ? std::string_view{"std::uint16_t"}
        : std::string_view{"std::uint32_t"};

    {
        std::ofstream hpp{hpp_path};
        if (!hpp) return std::unexpected{Error{ErrorCode::write_failed,
            std::format("cannot open {}", hpp_path)}};
        hpp << "// Generated by png2amiga-assets (tileset) — do not edit.\n";
        hpp << "// Shared tile pool for: " << stem << "\n";
        hpp << "#pragma once\n\n";
        hpp << "#include <array>\n";
        hpp << "#include <cstdint>\n\n";

        emit_ns_open(hpp, ns_parts);
        hpp << "\n";

        hpp << std::format("inline constexpr unsigned tile_w         = {};\n", pool.tile_w);
        hpp << std::format("inline constexpr unsigned tile_h         = {};\n", pool.tile_h);
        hpp << std::format("inline constexpr unsigned depth          = {};\n", pool.depth);
        hpp << std::format("inline constexpr unsigned bytes_per_row  = {};\n", pool.bytes_per_row);
        hpp << std::format("inline constexpr unsigned tile_bytes     = {};\n", pool.tile_bytes);
        hpp << std::format("inline constexpr unsigned num_tiles      = {};\n", pool.canonical_keys.size());
        hpp << std::format("inline constexpr unsigned palette_size   = {};\n", pool.palette.size());
        hpp << "\n";

        hpp << std::format(
            "extern const std::array<std::uint16_t, num_tiles * (tile_bytes / 2)> tiles_data;\n"
            "extern const std::array<{}, palette_size> palette;\n\n", pal_elem_type);

        hpp <<
            "[[nodiscard]] constexpr const std::uint16_t* tile_ptr(std::uint16_t idx) noexcept {\n"
            "    return tiles_data.data() + static_cast<std::size_t>(idx) * (tile_bytes / 2);\n"
            "}\n\n";

        emit_ns_close(hpp, ns_parts);
    }

    {
        std::ofstream cpp{cpp_path};
        if (!cpp) return std::unexpected{Error{ErrorCode::write_failed,
            std::format("cannot open {}", cpp_path)}};
        cpp << "// Generated by png2amiga-assets (tileset) — do not edit.\n";
        cpp << "#include \"" << std::filesystem::path{hpp_path}.filename().string() << "\"\n";
        if (opts.chip_attr == "PA_ASSET_CHIP") {
            cpp << "#include \"pa/chip_attr.hpp\"\n";
        }
        cpp << "\n";
        emit_ns_open(cpp, ns_parts);
        cpp << "\n";
        if (!opts.chip_attr.empty()) cpp << opts.chip_attr << "\n";
        cpp << "const std::array<std::uint16_t, num_tiles * (tile_bytes / 2)> tiles_data = {\n";
        emit_bitplane_words(cpp, pool.planes.data);
        cpp << "};\n\n";
        cpp << std::format("const std::array<{}, palette_size> palette = {{\n", pal_elem_type);
        emit_palette(cpp, pool.palette, opts.chipset);
        cpp << "};\n\n";
        emit_ns_close(cpp, ns_parts);
    }
    return {};
}

Result<void> write_tilemap(std::string_view base_path,
                           const tile_pack::MapResult& mr,
                           const Options& opts,
                           const MapWriteOptions& mopts) {
    auto ns_parts = split_namespace(opts.namespace_name);
    auto stem = basename_no_ext(base_path);
    auto hpp_path = std::string{base_path} + ".hpp";
    auto cpp_path = std::string{base_path} + ".cpp";

    {
        std::ofstream hpp{hpp_path};
        if (!hpp) return std::unexpected{Error{ErrorCode::write_failed,
            std::format("cannot open {}", hpp_path)}};
        hpp << "// Generated by png2amiga-assets (map) — do not edit.\n";
        hpp << "// Tilemap: " << stem << "\n";
        hpp << "// References tile pool: " << mopts.pool_namespace << "\n";
        hpp << "#pragma once\n\n";
        hpp << "#include <array>\n";
        hpp << "#include <cstdint>\n\n";
        hpp << "#include \"" << mopts.pool_header << "\"\n\n";

        emit_ns_open(hpp, ns_parts);
        hpp << "\n";

        // Re-export the pool's symbols so engine code can treat the map
        // namespace as a complete TilesetAsset adapter source.
        hpp << "using " << mopts.pool_namespace << "::tile_w;\n";
        hpp << "using " << mopts.pool_namespace << "::tile_h;\n";
        hpp << "using " << mopts.pool_namespace << "::depth;\n";
        hpp << "using " << mopts.pool_namespace << "::bytes_per_row;\n";
        hpp << "using " << mopts.pool_namespace << "::tile_bytes;\n";
        hpp << "using " << mopts.pool_namespace << "::num_tiles;\n";
        hpp << "using " << mopts.pool_namespace << "::palette_size;\n";
        hpp << "using " << mopts.pool_namespace << "::tile_ptr;\n";
        hpp << "using " << mopts.pool_namespace << "::palette;\n";
        hpp << "\n";

        hpp << std::format("inline constexpr unsigned map_w     = {};\n", mr.map_w);
        hpp << std::format("inline constexpr unsigned map_h     = {};\n", mr.map_h);
        hpp << std::format("inline constexpr unsigned num_cells = {};\n", mr.num_cells);
        hpp << "\n";

        hpp <<
            "struct MapCell {\n"
            "    std::uint16_t raw;\n"
            "    [[nodiscard]] constexpr std::uint16_t index() const noexcept {\n"
            "        return static_cast<std::uint16_t>(raw & 0x3FFFu);\n"
            "    }\n"
            "    [[nodiscard]] constexpr bool h_flip() const noexcept {\n"
            "        return (raw & 0x8000u) != 0;\n"
            "    }\n"
            "    [[nodiscard]] constexpr bool v_flip() const noexcept {\n"
            "        return (raw & 0x4000u) != 0;\n"
            "    }\n"
            "};\n"
            "static_assert(sizeof(MapCell) == 2);\n\n";

        hpp << "extern const std::array<MapCell, num_cells> tilemap;\n\n";

        hpp <<
            "[[nodiscard]] constexpr MapCell cell_at(unsigned x, unsigned y) noexcept {\n"
            "    return tilemap[y * map_w + x];\n"
            "}\n\n";

        emit_ns_close(hpp, ns_parts);
    }

    {
        std::ofstream cpp{cpp_path};
        if (!cpp) return std::unexpected{Error{ErrorCode::write_failed,
            std::format("cannot open {}", cpp_path)}};
        cpp << "// Generated by png2amiga-assets (map) — do not edit.\n";
        cpp << "#include \"" << std::filesystem::path{hpp_path}.filename().string() << "\"\n";
        if (opts.chip_attr == "PA_ASSET_CHIP") {
            cpp << "#include \"pa/chip_attr.hpp\"\n";
        }
        cpp << "\n";
        emit_ns_open(cpp, ns_parts);
        cpp << "\n";
        if (!opts.chip_attr.empty()) cpp << opts.chip_attr << "\n";
        cpp << "const std::array<MapCell, num_cells> tilemap = {\n";
        emit_tilemap(cpp, mr.tilemap, mr.map_w);
        cpp << "};\n\n";
        emit_ns_close(cpp, ns_parts);
    }
    return {};
}

namespace {

// Sanitize a single identifier component for use in a C++ enumerator.
std::string sanitize_ident(std::string_view s) {
    std::string out;
    out.reserve(s.size());
    for (char c : s) {
        out.push_back((std::isalnum(static_cast<unsigned char>(c)) ? c : '_'));
    }
    if (!out.empty() && std::isdigit(static_cast<unsigned char>(out.front()))) {
        out.insert(out.begin(), '_');
    }
    if (out.empty()) out = "_";
    return out;
}

} // namespace

Result<void> write_atlas_pack(std::string_view base_path,
                              const atlas_pack::PackResult& pack,
                              const Options& opts) {
    auto ns_parts = split_namespace(opts.namespace_name);
    auto hpp_path = std::string{base_path} + ".hpp";
    auto cpp_path = std::string{base_path} + ".cpp";

    auto pal_elem_type = (opts.chipset == Chipset::ocs)
        ? std::string_view{"std::uint16_t"}
        : std::string_view{"std::uint32_t"};

    // Deduplicate sanitized enum names in case two inputs share a base stem.
    std::vector<std::string> enum_names(pack.entries.size());
    std::unordered_map<std::string, int> used;
    for (std::size_t i = 0; i < pack.entries.size(); ++i) {
        auto base = sanitize_ident(pack.entries[i].name);
        auto& n = used[base];
        enum_names[i] = (n == 0) ? base : std::format("{}_{}", base, n);
        ++n;
    }

    // -------------------- header --------------------
    {
        std::ofstream hpp{hpp_path};
        if (!hpp) {
            return std::unexpected{Error{ErrorCode::write_failed,
                std::format("cannot open {}", hpp_path)}};
        }
        hpp << "// Generated by png2amiga-assets — do not edit.\n";
        hpp << "#pragma once\n\n";
        hpp << "#include <array>\n";
        hpp << "#include <cstdint>\n\n";

        emit_ns_open(hpp, ns_parts);
        hpp << "\n";

        hpp << std::format("inline constexpr unsigned page_w           = {};\n", pack.page_w);
        hpp << std::format("inline constexpr unsigned page_h           = {};\n", pack.page_h);
        hpp << std::format("inline constexpr unsigned depth            = {};\n", pack.depth);
        hpp << std::format("inline constexpr unsigned page_bpr         = {};\n", pack.page_bpr);
        hpp << std::format("inline constexpr unsigned page_bytes       = {};\n", pack.page_bytes);
        hpp << std::format("inline constexpr unsigned num_pages        = {};\n", pack.pages.size());
        hpp << std::format("inline constexpr unsigned num_entries      = {};\n", pack.entries.size());
        hpp << std::format("inline constexpr unsigned palette_size     = {};\n", pack.palette.size());
        hpp << std::format("inline constexpr bool     has_mask         = {};\n",
                           pack.has_mask ? "true" : "false");
        if (pack.has_mask) {
            hpp << std::format("inline constexpr unsigned page_mask_bytes  = {};\n", pack.page_mask_bytes);
        }
        hpp << "\n";

        hpp <<
            "struct Entry {\n"
            "    std::uint8_t  page;\n"
            "    std::uint16_t x;          // 16-px aligned\n"
            "    std::uint16_t y;\n"
            "    std::uint16_t w;          // logical width\n"
            "    std::uint16_t h;\n"
            "    std::uint16_t w_padded;   // 16-aligned storage width\n"
            "};\n\n";

        // Named enum for type-safe lookup.
        hpp << "enum class Id : std::uint16_t {\n";
        for (std::size_t i = 0; i < pack.entries.size(); ++i) {
            hpp << std::format("    {}{},\n", enum_names[i],
                               i == 0 ? " = 0" : "");
        }
        hpp << "};\n\n";

        hpp << std::format(
            "extern const std::array<std::uint16_t, num_pages * (page_bytes / 2)> pages_data;\n");
        if (pack.has_mask) {
            hpp << std::format(
                "extern const std::array<std::uint16_t, num_pages * (page_mask_bytes / 2)> masks_data;\n");
        }
        hpp << std::format(
            "extern const std::array<Entry, num_entries> entries;\n");
        hpp << std::format(
            "extern const std::array<{}, palette_size> palette;\n\n", pal_elem_type);

        hpp <<
            "[[nodiscard]] constexpr const Entry& get(Id id) noexcept {\n"
            "    return entries[static_cast<std::size_t>(id)];\n"
            "}\n"
            "[[nodiscard]] constexpr const std::uint16_t* page_ptr(unsigned p) noexcept {\n"
            "    return pages_data.data() + static_cast<std::size_t>(p) * (page_bytes / 2);\n"
            "}\n";
        if (pack.has_mask) {
            hpp <<
                "[[nodiscard]] constexpr const std::uint16_t* mask_page_ptr(unsigned p) noexcept {\n"
                "    return masks_data.data() + static_cast<std::size_t>(p) * (page_mask_bytes / 2);\n"
                "}\n";
        }
        hpp << "\n";

        emit_ns_close(hpp, ns_parts);
    }

    // -------------------- source --------------------
    {
        std::ofstream cpp{cpp_path};
        if (!cpp) {
            return std::unexpected{Error{ErrorCode::write_failed,
                std::format("cannot open {}", cpp_path)}};
        }
        cpp << "// Generated by png2amiga-assets — do not edit.\n";
        cpp << "#include \"" << std::filesystem::path{hpp_path}.filename().string() << "\"\n";
        if (opts.chip_attr == "PA_ASSET_CHIP") {
            cpp << "#include \"pa/chip_attr.hpp\"\n";
        }
        cpp << "\n";

        emit_ns_open(cpp, ns_parts);
        cpp << "\n";

        // pages_data
        if (!opts.chip_attr.empty()) cpp << opts.chip_attr << "\n";
        cpp << "const std::array<std::uint16_t, num_pages * (page_bytes / 2)> pages_data = {\n";
        for (auto& p : pack.pages) emit_bitplane_words(cpp, p.data);
        cpp << "};\n\n";

        // masks_data
        if (pack.has_mask) {
            if (!opts.chip_attr.empty()) cpp << opts.chip_attr << "\n";
            cpp << "const std::array<std::uint16_t, num_pages * (page_mask_bytes / 2)> masks_data = {\n";
            for (auto& m : pack.masks) emit_bitplane_words(cpp, m);
            cpp << "};\n\n";
        }

        // entries
        cpp << "const std::array<Entry, num_entries> entries = {{\n";
        for (auto& e : pack.entries) {
            cpp << std::format(
                "    Entry{{ {}, {}, {}, {}, {}, {} }},\n",
                e.page, e.x, e.y, e.w, e.h, e.w_padded);
        }
        cpp << "}};\n\n";

        cpp << std::format("const std::array<{}, palette_size> palette = {{\n", pal_elem_type);
        emit_palette(cpp, pack.palette, opts.chipset);
        cpp << "};\n\n";

        emit_ns_close(cpp, ns_parts);
    }

    return {};
}

} // namespace png2amiga::cpp_writer
