#pragma once

#include "amiga.hpp"
#include "dither.hpp"

namespace png2amiga::dither_tuning {

// Per-encoder-context dither defaults (Floyd-Steinberg-tuned).
//
// Empirical mean-PSNR sweep across the 10 example images for each
// supported (mode, depth, dpf, scap) combination. The table only
// applies when the user hasn't passed --dither-strength /
// --error-clamp on the CLI; explicit user values always win.
//
// Generated by tools/dither_tune.py (kept out of the binary; the
// numbers below are baked in).
struct Defaults {
    float strength;       // F-S residual scaling at scatter
    float error_clamp;    // per-channel OKLab clamp on read
};

// Identifies a mode-config bucket for tuning lookup. Anything not
// listed falls back to the conservative whole-codebase default
// (strength=1.0, error_clamp=0.35) — a safe pre-tuning baseline.
struct Context {
    amiga::Mode mode;
    int depth;            // bitplane depth as the encoder will use it
    bool dpf;             // dual-playfield
    bool scap;            // strips mid-line palette swaps
    bool copper;          // sliced per-line palette evolution
    amiga::Chipset chipset = amiga::Chipset::ocs;
    // Optional dither method — when provided, palette-aware methods
    // (opt-checker, knoll, yliluoma, yliluoma2) get a method-specific
    // optimal strength override. Default (none) keeps the F-S table.
    dither::Method method = dither::Method::floyd_steinberg;
};

Defaults defaults_for(const Context& ctx);

} // namespace png2amiga::dither_tuning
