#include "dither_tuning.hpp"

namespace png2amiga::dither_tuning {

// Empirical mean-PSNR maxima (Floyd-Steinberg) over the 10 example
// images, per encoder context. Generated by per-mode sweeps on
// scap-lores-5bpp; see commit log for grid details.
//
// Conservative default for unlisted contexts: strength=1.0,
// error_clamp=0.35 — the pre-tuning whole-codebase baseline.
//
// SCAP entries assume the CAP+SCAP layered encoder (b0be343) — SCAP
// rides on top of CAP-driven per-line palette evolution.
Defaults defaults_for(const Context& ctx) {
    constexpr Defaults kFallback{1.0f, 0.35f};

    // SCAP: layered on top of CAP. Tuned for the post-b0be343 encoder.
    if (ctx.scap) {
        if (ctx.dpf)        return Defaults{0.9f, 0.10f};   // 8 colours
        if (ctx.mode == amiga::Mode::ehb)
                            return Defaults{0.9f, 0.10f};   // 64 effective
        if (ctx.mode == amiga::Mode::lores && ctx.depth == 5)
                            return Defaults{0.9f, 0.35f};   // 32 colours
        return kFallback;
    }

    // CAP (per-line palette evolution, no SCAP).
    if (ctx.copper) {
        if (ctx.mode == amiga::Mode::ehb)
                            return Defaults{0.9f, 0.35f};
        if (ctx.mode == amiga::Mode::lores) {
            if (ctx.chipset == amiga::Chipset::aga) {
                switch (ctx.depth) {
                    case 4: return Defaults{1.0f, 0.10f};
                    case 5: return Defaults{1.0f, 0.10f};
                    case 6: return Defaults{1.0f, 0.06f};
                    default: break;  // depths 7-8 swept but values pending
                }
            } else {
                switch (ctx.depth) {
                    case 2: return Defaults{1.0f, 0.10f};
                    case 3: return Defaults{1.0f, 0.20f};
                    case 4: return Defaults{1.0f, 0.04f};
                    case 5: return Defaults{1.0f, 0.10f};
                    default: break;
                }
            }
        }
        return kFallback;
    }

    // Standard modes (no copper, no SCAP).
    if (ctx.mode == amiga::Mode::ehb) return Defaults{0.9f, 0.35f};
    if (ctx.mode == amiga::Mode::lores) {
        switch (ctx.depth) {
            case 1: return Defaults{1.0f, 0.35f};
            case 2: return Defaults{0.8f, 0.10f};
            case 3: return Defaults{0.9f, 0.35f};
            case 4: return Defaults{0.9f, 0.20f};
            case 5: return Defaults{0.9f, 0.35f};
            default: break;
        }
    }

    return kFallback;
}

} // namespace png2amiga::dither_tuning
