#include "dither_tuning.hpp"

namespace png2amiga::dither_tuning {

// Empirical mean-PSNR maxima over the 10 example images.
//
// Two layers:
//   1. Palette-aware ordered methods (opt-checker, knoll, yliluoma,
//      yliluoma2) get per-method optimal strength — their dither
//      response is method-dependent, not mode-dependent.
//   2. Everything else uses the per-encoder-context Floyd-Steinberg
//      tuned table below. Generated by per-mode sweeps on
//      scap-lores-5bpp; see commit log for grid details.
//
// Conservative default for unlisted contexts: strength=1.0,
// error_clamp=0.35 — the pre-tuning whole-codebase baseline.
//
// SCAP entries assume the CAP+SCAP layered encoder with two-pass
// refinement (commit 9f51baa) — SCAP rides on top of CAP-driven
// per-line palette evolution.
Defaults defaults_for(const Context& ctx) {
    constexpr Defaults kFallback{1.0f, 0.35f};

    // ---- Palette-aware ordered methods: per-method optimal strength
    // (mean-PSNR sweep over the 10 example images, lores depth=5,
    // strengths 0.50, 0.60, 0.70, 0.80, 0.85, 0.90, 0.95, 1.00).
    // These methods dither via per-pixel mixing-plan + Bayer index, so
    // optimal strength is method-dependent rather than mode-dependent.
    // error_clamp is unused by these methods but kept at 0.35 for the
    // CLI surface consistency.
    switch (ctx.method) {
    // Palette-aware ordered:
    case dither::Method::opt_checker: return Defaults{0.85f, 0.35f};  // 32.495 dB
    case dither::Method::opt_line:    return Defaults{0.70f, 0.35f};  // 32.421 dB
    case dither::Method::opt_line_checker:
                                      return Defaults{1.00f, 0.35f};  // 32.563 dB (flat below)
    case dither::Method::knoll:       return Defaults{0.80f, 0.35f};  // 32.583 dB (after round() fix)
    case dither::Method::tri_tone:    return Defaults{1.00f, 0.35f};  // 32.500 dB (flat below 1.0)
    case dither::Method::yliluoma1:   return Defaults{0.50f, 0.35f};  // 31.055 dB (monotone declining)
    case dither::Method::yliluoma:    return Defaults{0.70f, 0.35f};  // 32.296 dB
    case dither::Method::yliluoma2:   return Defaults{0.60f, 0.35f};  // 32.007 dB
    // Error diffusion family (lores d=5 sweep — strength only; the
    // mode-context table below still owns error_clamp tuning):
    case dither::Method::atkinson:        return Defaults{0.85f, 0.35f};  // 33.799 dB (OKLab-tuned kernel)
    case dither::Method::sierra_lite:     return Defaults{0.85f, 0.35f};  // 33.836 dB
    case dither::Method::stucki:          return Defaults{0.85f, 0.35f};  // 33.597 dB (OKLab-tuned kernel)
    case dither::Method::jarvis:          return Defaults{0.95f, 0.35f};  // 33.606 dB (OKLab-tuned kernel)
    case dither::Method::ostromoukhov:    return Defaults{0.85f, 0.35f};  // 33.757 dB
    case dither::Method::gilbert:         return Defaults{0.85f, 0.35f};  // 33.750 dB
    case dither::Method::riemersma:       return Defaults{0.70f, 0.35f};  // 32.593 dB
    case dither::Method::structure_fs:    return Defaults{0.80f, 0.35f};  // 29.184 dB
    case dither::Method::contrast_fs:     return Defaults{1.00f, 0.35f};  // 28.574 dB
    case dither::Method::zhoufang:        return Defaults{0.60f, 0.35f};  // 30.436 dB
    // DBS: warm-starts from FS, then optimises blurred-OKLab cost via
    // greedy toggles. Use the same context-tuned (mode/depth/CAP/SCAP)
    // FS defaults as plain Floyd-Steinberg — DBS converges to a local
    // minimum, so the warm start matters and per-context FS values are
    // already empirically optimal for that bucket. Falling through.
    case dither::Method::dbs: break;
    default: break;
    }

    // ---- SCAP: layered on top of CAP. -----------------------------------
    if (ctx.scap) {
        if (ctx.dpf)        return Defaults{0.9f, 0.10f};   // 8 colours
        if (ctx.mode == amiga::Mode::ehb)
                            return Defaults{0.9f, 0.10f};   // 64 effective
        return kFallback;
    }

    // ---- HAM (own dither pipeline) --------------------------------------
    // HAM dithers via the beam-search pre-dither in ham.cpp; the strength
    // and error_clamp still feed through but the response is muted because
    // most of the work is the DP search itself. Sweep optima:
    if (ctx.mode == amiga::Mode::ham6) {
        // HAM6+CAP: st=0.8, ec=0.04 (PSNR 41.49 mean)
        // HAM6 alone: st=1.0, ec=0.04 (PSNR 40.34 mean)
        if (ctx.copper) return Defaults{0.8f, 0.04f};
        return Defaults{1.0f, 0.04f};
    }
    if (ctx.mode == amiga::Mode::ham8) {
        // HAM8+CAP/AGA: st=0.7, ec=0.04 (PSNR 49.77 mean)
        // HAM8 alone:   st=0.9, ec=0.10 (PSNR 46.38 mean)
        if (ctx.copper) return Defaults{0.7f, 0.04f};
        return Defaults{0.9f, 0.10f};
    }
    // HAM4/HAM5/HAM7 not in the sweep — assume their tuning follows
    // HAM6/HAM8 by interpolation. Conservative: leave on kFallback.

    // ---- CAP (per-line palette evolution, no SCAP) ----------------------
    if (ctx.copper) {
        if (ctx.mode == amiga::Mode::ehb)
                            return Defaults{0.9f, 0.20f};   // mean 37.83
        if (ctx.mode == amiga::Mode::lores) {
            if (ctx.chipset == amiga::Chipset::aga) {
                switch (ctx.depth) {
                    case 4: return Defaults{1.0f, 0.10f};   // mean 33.20
                    case 5: return Defaults{1.0f, 0.10f};   // mean 37.19
                    case 6: return Defaults{1.0f, 0.06f};   // mean 44.33
                    case 8: return Defaults{1.0f, 0.04f};   // mean 48.14
                    default: break;
                }
            } else {
                switch (ctx.depth) {
                    case 2: return Defaults{1.0f, 0.10f};   // mean 21.76
                    case 3: return Defaults{1.0f, 0.20f};   // mean 26.89
                    case 4: return Defaults{1.0f, 0.04f};   // mean 30.92
                    case 5: return Defaults{1.0f, 0.10f};   // mean 35.61
                    default: break;
                }
            }
        }
        if (ctx.mode == amiga::Mode::hires) {
            switch (ctx.depth) {
                case 3: return Defaults{1.0f, 0.10f};       // mean 26.48
                case 4: return Defaults{1.0f, 0.20f};       // mean 30.68
                default: break;
            }
        }
        return kFallback;
    }

    // ---- Standard modes (no copper, no SCAP) ----------------------------
    if (ctx.mode == amiga::Mode::ehb) return Defaults{0.9f, 0.35f};
    if (ctx.mode == amiga::Mode::lores) {
        switch (ctx.depth) {
            case 1: return Defaults{1.0f, 0.35f};
            case 2: return Defaults{0.8f, 0.10f};
            case 3: return Defaults{0.9f, 0.35f};
            case 4: return Defaults{0.9f, 0.20f};
            case 5: return Defaults{0.9f, 0.35f};
            default: break;
        }
    }

    return kFallback;
}

} // namespace png2amiga::dither_tuning
