#pragma once

#include "amiga.hpp"
#include "color_space.hpp"
#include "types.hpp"

#include <algorithm>
#include <array>
#include <cstdint>
#include <functional>
#include <utility>
#include <string_view>
#include <vector>

namespace png2amiga::palette {

// ---------------------------------------------------------------------------
// OCS/ECS 12-bit color: 4 bits per channel (0-15 mapped to 0x00-0xFF)
// Amiga hardware stores R/G/B nibbles: 0xRGB
// ---------------------------------------------------------------------------

constexpr Color3f ocs_to_linear(std::uint16_t rgb12) noexcept {
    auto r4 = static_cast<std::uint8_t>((rgb12 >> 8) & 0xF);
    auto g4 = static_cast<std::uint8_t>((rgb12 >> 4) & 0xF);
    auto b4 = static_cast<std::uint8_t>(rgb12 & 0xF);
    // 4-bit to 8-bit: replicate nibble (0xN -> 0xNN)
    auto r8 = static_cast<std::uint8_t>((r4 << 4) | r4);
    auto g8 = static_cast<std::uint8_t>((g4 << 4) | g4);
    auto b8 = static_cast<std::uint8_t>((b4 << 4) | b4);
    return color_space::srgb_u8_to_linear(r8, g8, b8);
}

// OCS 12-bit quantizer: snap a linear-RGB color to the perceptually-
// nearest entry in the 4096-color OCS gamut.
//
// Algorithm: pre-baked per-seed candidate table (auto-generated by
// tools/gen_ocs_cand_table.cpp at N=1024). For each of the 4096
// sRGB-rounded seed nibble triples we store the small list (mean ~12,
// max 20) of OCS codes that can ever be the OKLab-nearest for any input
// whose seed is that triple. Runtime: per-channel sRGB-round to find
// seed, then brute-force OKLab distance over that seed's candidate list.
// Verified by tools/seed_window_audit.cpp to give bit-identical results
// to the full 4096-candidate brute-force search across all 16.7M 8-bit
// sRGB inputs (zero mismatches).
//
// Why OKLab-nearest rather than per-channel sRGB rounding directly: in
// dark regions, OCS levels are crowded together in linear light, so
// per-channel rounding picks perceptually-wrong neighbours. Measured
// +4.70 to +10.66 SSIMULACRA2 on HDR/banded content; wash (~±1) on
// smooth photographic content.
namespace detail {
struct OcsOklabTable {
    std::array<color_space::OKLab, 4096> oklab;
    OcsOklabTable() {
        for (std::uint16_t code = 0; code < 4096; ++code) {
            auto r4 = static_cast<std::uint8_t>((code >> 8) & 0xF);
            auto g4 = static_cast<std::uint8_t>((code >> 4) & 0xF);
            auto b4 = static_cast<std::uint8_t>(code & 0xF);
            auto r8 = static_cast<std::uint8_t>((r4 << 4) | r4);
            auto g8 = static_cast<std::uint8_t>((g4 << 4) | g4);
            auto b8 = static_cast<std::uint8_t>((b4 << 4) | b4);
            oklab[code] = color_space::linear_to_oklab(
                color_space::srgb_u8_to_linear(r8, g8, b8));
        }
    }
};
inline const OcsOklabTable& ocs_oklab_table() {
    static const OcsOklabTable t;
    return t;
}

// Per-seed candidate-list table, defined in src/ocs_cand_table.cpp.
// `offsets` has 4097 entries; codes for seed s live in
// [offsets[s], offsets[s+1]).
struct OcsCandTable {
    const std::uint32_t* offsets;
    const std::uint16_t* codes;
    std::size_t          codes_size;
};
const OcsCandTable& ocs_cand_table() noexcept;
}  // namespace detail

inline std::uint16_t linear_to_ocs(Color3f color) noexcept {
    auto t = color_space::linear_to_oklab(color);
    auto& tab = detail::ocs_oklab_table().oklab;
    auto& ct = detail::ocs_cand_table();

    auto srgb = color_space::linear_to_srgb(color).clamped();
    int seed_r = std::clamp(static_cast<int>(srgb.r * 15.0f + 0.5f), 0, 15);
    int seed_g = std::clamp(static_cast<int>(srgb.g * 15.0f + 0.5f), 0, 15);
    int seed_b = std::clamp(static_cast<int>(srgb.b * 15.0f + 0.5f), 0, 15);
    int seed = (seed_r << 8) | (seed_g << 4) | seed_b;

    std::uint16_t best = 0;
    float best_d = std::numeric_limits<float>::infinity();
    const std::uint16_t* p = ct.codes + ct.offsets[seed];
    const std::uint16_t* end = ct.codes + ct.offsets[seed + 1];
    for (; p != end; ++p) {
        const auto& e = tab[*p];
        float dL = t.L - e.L;
        float da = t.a - e.a;
        float db = t.b - e.b;
        float d = dL * dL + da * da + db * db;
        if (d < best_d) { best_d = d; best = *p; }
    }
    return best;
}

// AGA 24-bit: split into high and low nibble words for LOCT register.
// hi = upper 4 bits per channel (0x0RGB), lo = lower 4 bits (0x0RGB).
struct AGA_HiLo { std::uint16_t hi; std::uint16_t lo; };
constexpr AGA_HiLo linear_to_aga_hilo(Color3f color) noexcept {
    auto srgb = color_space::linear_to_srgb(color).clamped();
    auto r8 = static_cast<int>(srgb.r * 255.0f + 0.5f) & 0xFF;
    auto g8 = static_cast<int>(srgb.g * 255.0f + 0.5f) & 0xFF;
    auto b8 = static_cast<int>(srgb.b * 255.0f + 0.5f) & 0xFF;
    auto hi = static_cast<std::uint16_t>(((r8 >> 4) << 8) | ((g8 >> 4) << 4) | (b8 >> 4));
    auto lo = static_cast<std::uint16_t>(((r8 & 0xF) << 8) | ((g8 & 0xF) << 4) | (b8 & 0xF));
    return {hi, lo};
}

// ---------------------------------------------------------------------------
// Atari STF 9-bit color: 3 bits per channel (0-7), 512 possible colors
// Stored as 0x0RGB where each nibble is 0-7
// ---------------------------------------------------------------------------

constexpr Color3f stf_to_linear(std::uint16_t rgb9) noexcept {
    auto r3 = static_cast<std::uint8_t>((rgb9 >> 8) & 0x7);
    auto g3 = static_cast<std::uint8_t>((rgb9 >> 4) & 0x7);
    auto b3 = static_cast<std::uint8_t>(rgb9 & 0x7);
    // 3-bit to 8-bit: replicate bits (abc -> abcabcab)
    auto r8 = static_cast<std::uint8_t>((r3 << 5) | (r3 << 2) | (r3 >> 1));
    auto g8 = static_cast<std::uint8_t>((g3 << 5) | (g3 << 2) | (g3 >> 1));
    auto b8 = static_cast<std::uint8_t>((b3 << 5) | (b3 << 2) | (b3 >> 1));
    return color_space::srgb_u8_to_linear(r8, g8, b8);
}

constexpr std::uint16_t linear_to_stf(Color3f color) noexcept {
    auto srgb = color_space::linear_to_srgb(color).clamped();
    auto r3 = static_cast<std::uint16_t>(
        static_cast<int>(srgb.r * 7.0f + 0.5f) & 0x7);
    auto g3 = static_cast<std::uint16_t>(
        static_cast<int>(srgb.g * 7.0f + 0.5f) & 0x7);
    auto b3 = static_cast<std::uint16_t>(
        static_cast<int>(srgb.b * 7.0f + 0.5f) & 0x7);
    return static_cast<std::uint16_t>((r3 << 8) | (g3 << 4) | b3);
}

constexpr Color3f quantize_to_stf(Color3f color) noexcept {
    return stf_to_linear(linear_to_stf(color));
}

// ---------------------------------------------------------------------------
// Commodore 64 / VIC-II 16-color hardware palette. The VIC-II's analogue
// composite output doesn't have a unique sRGB ground-truth — different
// research efforts produced slightly different RGB tables. We use Pepto's
// 2001 derivation as the default (widely accepted reference; see
// pepto.de/projects/colorvic/). Indexed 0..15 in standard VIC-II order:
// black, white, red, cyan, purple, green, blue, yellow, orange, brown,
// light red, dark grey, medium grey, light green, light blue, light grey.
// ---------------------------------------------------------------------------
inline constexpr std::array<std::uint32_t, 16> kC64Pepto = {
    0x000000, 0xFFFFFF, 0x68372B, 0x70A4B2,
    0x6F3D86, 0x588D43, 0x352879, 0xB8C76F,
    0x6F4F25, 0x433900, 0x9A6759, 0x444444,
    0x6C6C6C, 0x9AD284, 0x6C5EB5, 0x959595,
};

// ---------------------------------------------------------------------------
// CGA 16-color master palette (IRGB, fixed at hardware). Canonical "IBM
// Color/Graphics Monitor Adaptor" values (sRGB). Values sourced from the
// IBM Technical Reference & widely-reproduced CGA color tables.
// Indexed 0..15: black, blue, green, cyan, red, magenta, brown, light gray,
// dark gray, light blue, light green, light cyan, light red, light magenta,
// yellow, white.
// ---------------------------------------------------------------------------
inline constexpr std::array<std::uint32_t, 16> kCgaHw = {
    0x000000, 0x0000AA, 0x00AA00, 0x00AAAA,
    0xAA0000, 0xAA00AA, 0xAA5500, 0xAAAAAA,
    0x555555, 0x5555FF, 0x55FF55, 0x55FFFF,
    0xFF5555, 0xFF55FF, 0xFFFF55, 0xFFFFFF,
};

// CGA 320x200 4-color fixed palettes.
// Slot 0 = background (variable, defaults to black = 0).
// Slots 1-3 = fixed by palette (0 or 1) × intensity (low or high).
//   0-low:   green (2), red (4), brown (6)
//   0-high:  light green (10), light red (12), yellow (14)
//   1-low:   cyan (3), magenta (5), light gray (7)    [default]
//   1-high:  light cyan (11), light magenta (13), white (15)
// See: https://en.wikipedia.org/wiki/Color_Graphics_Adapter
enum class CgaPalette : unsigned char {
    p0_low, p0_high, p1_low, p1_high,
};

constexpr std::array<std::uint8_t, 3> cga_palette_indices(CgaPalette p) noexcept {
    switch (p) {
    case CgaPalette::p0_low:  return { 2,  4,  6};
    case CgaPalette::p0_high: return {10, 12, 14};
    case CgaPalette::p1_low:  return { 3,  5,  7};
    case CgaPalette::p1_high: return {11, 13, 15};
    }
    return {11, 13, 15};
}

// Build a 4-color CGA palette as Color3f linear colors.
// bg_index selects the background color (0..15 in master palette).
inline std::array<Color3f, 4> cga_build_palette(CgaPalette p,
                                                std::uint8_t bg_index = 0) {
    auto hw_idx = cga_palette_indices(p);
    std::array<Color3f, 4> pal{};
    pal[0] = color_space::srgb_hex_to_linear(kCgaHw[bg_index & 0xF]);
    for (std::size_t i = 0; i < 3; ++i) {
        pal[i + 1] = color_space::srgb_hex_to_linear(kCgaHw[hw_idx[i]]);
    }
    return pal;
}

// ---------------------------------------------------------------------------
// CGA composite 16-color artifact palette.
//
// In 320x200 4-color mode on a composite monitor, adjacent pairs of 2bpp
// pixels form a 4-bit NTSC phase pattern that the decoder interprets as
// one of 16 hue/brightness combinations. Used by King's Quest (early IBM
// releases), Space Quest, 8088 MPH demo, AREA 5150, etc.
//
// The actual decoded colors depend on monitor tint/saturation (a physical
// knob on the CRT); these values are a representative "old CGA composite"
// palette from reenigne's calibration work and match what DOSBox renders
// in composite mode by default. The palette is the same 16 RGBI entries
// that CGA normally produces digitally, but rearranged — the 4-bit pattern
// index N does NOT map to CGA master color N. We store it explicitly.
//
// The mapping from pattern to color is (approximately — monitor-dependent):
//   0000 → black       1000 → grey
//   0001 → blue        1001 → light blue
//   0010 → green       1010 → light green
//   0011 → cyan        1011 → light cyan
//   0100 → red         1100 → light red
//   0101 → magenta     1101 → light magenta
//   0110 → brown       1110 → yellow
//   0111 → light grey  1111 → white
// That is: pattern N corresponds to RGBI color N via the standard "old CGA"
// composite decoder. This is the simplest reasonable model; tools like
// DOSBox support multiple palettes (old/new CGA, adjustable tint).
// ---------------------------------------------------------------------------
inline constexpr std::array<std::uint32_t, 16> kCgaCompositeOld = {
    // Old-CGA composite (pre-1983 IBM 5150/5160). Each 4-bit pattern value
    // (index into this array) is the NTSC-decoded color that pixel-pair
    // pattern produces.
    0x000000, 0x0000AA, 0x00AA00, 0x00AAAA,
    0xAA0000, 0xAA00AA, 0xAA5500, 0xAAAAAA,
    0x555555, 0x5555FF, 0x55FF55, 0x55FFFF,
    0xFF5555, 0xFF55FF, 0xFFFF55, 0xFFFFFF,
};

// Build the 16-color composite palette as linear Color3f.
inline std::array<Color3f, 16> cga_composite_palette() {
    std::array<Color3f, 16> pal{};
    for (std::size_t i = 0; i < 16; ++i) {
        pal[i] = color_space::srgb_hex_to_linear(kCgaCompositeOld[i]);
    }
    return pal;
}

// Given a color index 0..15, return the 4-bit pixel pair pattern that
// produces it on a composite monitor. With our "pattern == RGBI index"
// model this is identity, but centralised here so a future mode-tweaked
// palette (new CGA, artifact shifts) can remap without touching callers.
inline constexpr std::uint8_t cga_composite_pattern(std::uint8_t idx) noexcept {
    return idx & 0xF;
}

// ---------------------------------------------------------------------------
// EGA 6-bit color: 2 bits per channel, 64 possible colors. Stored as a
// single byte in R'G'B'RGB order (primary RGB bits 0-2, secondary bits 3-5),
// where primary = 2/3 intensity and secondary = 1/3. Combined 4 levels per
// channel: 0, 85 (0x55), 170 (0xAA), 255 (0xFF).
//
// We encode/decode using a symmetrical 2-bit-per-channel layout here
// (rrggbb, 2 bits each) and translate to IrgbIRGB at output time. This
// matches our "snap color to 4 levels per channel" quantization goal.
// ---------------------------------------------------------------------------

constexpr Color3f ega_to_linear(std::uint8_t rgb6) noexcept {
    auto r2 = static_cast<std::uint8_t>((rgb6 >> 4) & 0x3);
    auto g2 = static_cast<std::uint8_t>((rgb6 >> 2) & 0x3);
    auto b2 = static_cast<std::uint8_t>(rgb6 & 0x3);
    // 2-bit to 8-bit: replicate the 2-bit pattern four times.
    // 0b00 -> 0x00, 0b01 -> 0x55, 0b10 -> 0xAA, 0b11 -> 0xFF.
    auto expand = [](std::uint8_t v) noexcept -> std::uint8_t {
        return static_cast<std::uint8_t>((v << 6) | (v << 4) | (v << 2) | v);
    };
    return color_space::srgb_u8_to_linear(expand(r2), expand(g2), expand(b2));
}

constexpr std::uint8_t linear_to_ega(Color3f color) noexcept {
    auto srgb = color_space::linear_to_srgb(color).clamped();
    auto r2 = static_cast<std::uint8_t>(
        static_cast<int>(srgb.r * 3.0f + 0.5f) & 0x3);
    auto g2 = static_cast<std::uint8_t>(
        static_cast<int>(srgb.g * 3.0f + 0.5f) & 0x3);
    auto b2 = static_cast<std::uint8_t>(
        static_cast<int>(srgb.b * 3.0f + 0.5f) & 0x3);
    return static_cast<std::uint8_t>((r2 << 4) | (g2 << 2) | b2);
}

constexpr Color3f quantize_to_ega(Color3f color) noexcept {
    return ega_to_linear(linear_to_ega(color));
}

// Convert rrggbb (2-bit-per-channel) to the EGA hardware's IrgbIRGB
// 6-bit palette byte. IRGB bits = primary (2/3 intensity); irgb = secondary
// (1/3). Level-2 maps to primary-only; level-3 to primary+secondary;
// level-1 to secondary-only.
constexpr std::uint8_t ega_to_hw(std::uint8_t rrggbb) noexcept {
    auto r2 = static_cast<std::uint8_t>((rrggbb >> 4) & 0x3);
    auto g2 = static_cast<std::uint8_t>((rrggbb >> 2) & 0x3);
    auto b2 = static_cast<std::uint8_t>(rrggbb & 0x3);
    auto map = [](std::uint8_t v) -> std::pair<std::uint8_t, std::uint8_t> {
        // Returns {primary_bit, secondary_bit}
        switch (v) {
        case 0:  return {0, 0};  // 0x00
        case 1:  return {0, 1};  // 0x55
        case 2:  return {1, 0};  // 0xAA
        default: return {1, 1};  // 0xFF
        }
    };
    auto [rp, rs] = map(r2);
    auto [gp, gs] = map(g2);
    auto [bp, bs] = map(b2);
    // IrgbIRGB bit layout (bit 5..0): R' G' B' R G B (R'=secondary red, R=primary)
    return static_cast<std::uint8_t>(
        (rs << 5) | (gs << 4) | (bs << 3) |
        (rp << 2) | (gp << 1) | (bp << 0));
}

// ---------------------------------------------------------------------------
// VGA 18-bit color: 6 bits per channel, 262144 possible colors
// (The VGA DAC takes 6-bit values per channel, 0-63.)
// Stored in a uint32_t as 0x00RRGGBB where each byte is 0-63.
// ---------------------------------------------------------------------------

constexpr Color3f vga_to_linear(std::uint32_t rgb18) noexcept {
    auto r6 = static_cast<std::uint8_t>((rgb18 >> 16) & 0x3F);
    auto g6 = static_cast<std::uint8_t>((rgb18 >> 8) & 0x3F);
    auto b6 = static_cast<std::uint8_t>(rgb18 & 0x3F);
    // 6-bit to 8-bit: replicate top 2 bits in low 2 bits.
    auto r8 = static_cast<std::uint8_t>((r6 << 2) | (r6 >> 4));
    auto g8 = static_cast<std::uint8_t>((g6 << 2) | (g6 >> 4));
    auto b8 = static_cast<std::uint8_t>((b6 << 2) | (b6 >> 4));
    return color_space::srgb_u8_to_linear(r8, g8, b8);
}

constexpr std::uint32_t linear_to_vga(Color3f color) noexcept {
    auto srgb = color_space::linear_to_srgb(color).clamped();
    auto r6 = static_cast<std::uint32_t>(srgb.r * 63.0f + 0.5f) & 0x3F;
    auto g6 = static_cast<std::uint32_t>(srgb.g * 63.0f + 0.5f) & 0x3F;
    auto b6 = static_cast<std::uint32_t>(srgb.b * 63.0f + 0.5f) & 0x3F;
    return (r6 << 16) | (g6 << 8) | b6;
}

constexpr Color3f quantize_to_vga(Color3f color) noexcept {
    return vga_to_linear(linear_to_vga(color));
}

// ---------------------------------------------------------------------------
// AGA 24-bit color: 8 bits per channel
// Stored as 0x00RRGGBB
// ---------------------------------------------------------------------------

constexpr Color3f aga_to_linear(std::uint32_t rgb24) noexcept {
    auto r = static_cast<std::uint8_t>((rgb24 >> 16) & 0xFF);
    auto g = static_cast<std::uint8_t>((rgb24 >> 8) & 0xFF);
    auto b = static_cast<std::uint8_t>(rgb24 & 0xFF);
    return color_space::srgb_u8_to_linear(r, g, b);
}

constexpr std::uint32_t linear_to_aga(Color3f color) noexcept {
    auto srgb = color_space::linear_to_srgb(color).clamped();
    auto r = static_cast<std::uint32_t>(srgb.r * 255.0f + 0.5f) & 0xFF;
    auto g = static_cast<std::uint32_t>(srgb.g * 255.0f + 0.5f) & 0xFF;
    auto b = static_cast<std::uint32_t>(srgb.b * 255.0f + 0.5f) & 0xFF;
    return (r << 16) | (g << 8) | b;
}

// ---------------------------------------------------------------------------
// Quantize a Color3f to OCS 12-bit precision (snap to nearest OCS color)
// ---------------------------------------------------------------------------

constexpr Color3f quantize_to_ocs(Color3f color) noexcept {
    return ocs_to_linear(linear_to_ocs(color));
}

// ---------------------------------------------------------------------------
// Generate full OCS palette (all 4096 possible 12-bit colors)
// ---------------------------------------------------------------------------

inline Palette all_ocs_colors() {
    Palette pal;
    pal.name = "ocs-4096";
    pal.colors.reserve(4096);
    for (std::uint16_t i = 0; i < 4096; ++i) {
        pal.colors.push_back(ocs_to_linear(i));
    }
    return pal;
}

// Full 64-entry EGA color gamut (every 2-bit-per-channel combination).
// Useful for brute-force palette selection on EGA modes — the continuous
// median-cut often picks nearby colors that collapse to the same 64-slot
// value after snapping, yielding too few distinct output colors.
inline Palette all_ega_colors() {
    Palette pal;
    pal.name = "ega-64";
    pal.colors.reserve(64);
    for (std::uint16_t i = 0; i < 64; ++i) {
        pal.colors.push_back(ega_to_linear(static_cast<std::uint8_t>(i)));
    }
    return pal;
}

// ---------------------------------------------------------------------------
// Commonly used Amiga palettes
// ---------------------------------------------------------------------------

// Default Workbench 2.0 palette (4 colors)
#if defined(__GNUC__) && !defined(__clang__)
constexpr
#else
inline
#endif
auto workbench_20_colors() {
    return std::array<Color3f, 4>{
        color_space::srgb_hex_to_linear(0x959595),  // Grey (background)
        color_space::srgb_hex_to_linear(0x000000),  // Black
        color_space::srgb_hex_to_linear(0xFFFFFF),  // White
        color_space::srgb_hex_to_linear(0x3B67A2),  // Blue
    };
}

// Classic Amiga boing ball red/white
#if defined(__GNUC__) && !defined(__clang__)
constexpr
#else
inline
#endif
auto boing_ball_colors() {
    return std::array<Color3f, 2>{
        color_space::srgb_hex_to_linear(0xFFFFFF),  // White
        color_space::srgb_hex_to_linear(0xFF0000),  // Red
    };
}

// ---------------------------------------------------------------------------
// Palette lookup by name
// ---------------------------------------------------------------------------

inline Palette by_name(std::string_view name) {
    if (name == "ocs-4096" || name == "ocs") {
        return all_ocs_colors();
    }
    if (name == "workbench") {
        auto colors = workbench_20_colors();
        return Palette{"workbench", {colors.begin(), colors.end()}};
    }
    // Default: full OCS palette for maximum flexibility
    return all_ocs_colors();
}

// ---------------------------------------------------------------------------
// Find nearest palette color (brute force, perceptual in OKLab)
// ---------------------------------------------------------------------------

inline std::size_t find_nearest(Color3f color,
                                std::span<const Color3f> palette) noexcept {
    std::size_t best = 0;
    float best_dist = color_space::perceptual_distance_sq(color, palette[0]);

    for (std::size_t i = 1; i < palette.size(); ++i) {
        float dist = color_space::perceptual_distance_sq(color, palette[i]);
        if (dist < best_dist) {
            best_dist = dist;
            best = i;
        }
    }
    return best;
}

// ---------------------------------------------------------------------------
// EHB (Extra Half-Brite) palette generation
//
// Given a set of 32 base colors, produce 64-color palette where entries
// 32-63 are the half-brightness versions of entries 0-31.
// The Amiga hardware generates half-brite by halving each RGB component.
// We compute this in sRGB space (as the hardware operates on DAC values).
// ---------------------------------------------------------------------------

// Half-brite a base linear-RGB colour, matching the OCS hardware DAC:
// the 4-bit per-channel nibble is shifted right by one (truncating),
// then re-replicated to 8-bit. EHB is fundamentally an OCS feature, so
// we snap the input to OCS before halving — even AGA-EHB outputs OCS-
// quantised colours through the EHB path. The previous implementation
// used sRGB × 0.5 which is wrong for OCS: e.g. halve(0x33) is 0x11
// (nibble 3 >> 1 = 1, nibble-replicated), not 0x19 (sRGB / 2).
// Single source of truth replacing scap::half_brite + copper::halve_brite.
inline Color3f half_brite(const Color3f& c) {
    auto code = linear_to_ocs(c);
    auto r4 = static_cast<std::uint16_t>((code >> 8) & 0xF);
    auto g4 = static_cast<std::uint16_t>((code >> 4) & 0xF);
    auto b4 = static_cast<std::uint16_t>(code & 0xF);
    std::uint16_t halved =
        static_cast<std::uint16_t>(((r4 >> 1) << 8) | ((g4 >> 1) << 4) | (b4 >> 1));
    return ocs_to_linear(halved);
}

inline Palette make_ehb_palette(std::span<const Color3f> base_colors) {
    Palette pal;
    pal.name = "ehb";
    pal.colors.reserve(64);

    // First 32 entries: base colors
    for (auto& c : base_colors) {
        pal.colors.push_back(c);
    }
    // Pad to 32 if fewer were provided
    while (pal.colors.size() < 32) {
        pal.colors.push_back(Color3f{0.0f, 0.0f, 0.0f});
    }

    // Entries 32-63: half-brightness copies
    for (std::size_t i = 0; i < 32; ++i) {
        pal.colors.push_back(half_brite(pal.colors[i]));
    }

    return pal;
}

// Pair-aware k-means refinement for EHB.
//
// Median-cut alone picks 32 base colors that span the source's dominant
// clusters; deriving the half-brite copies as base/2 then leaves the
// dark half of the gamut covered "for free" but unoptimised. The
// hardware-tied pairing (hb = base/2 in sRGB DAC space) means that
// where you put a base color also dictates where its half-brite copy
// lands, so the optimum 32-base set is the one that minimises total
// squared error over BOTH halves jointly.
//
// Per iteration:
//   1. Assign each pixel to its OKLab-nearest of the 64 effective colors.
//   2. For each slot k, separate the base assignments B_k from the
//      half-brite assignments H_k.
//   3. Solve in sRGB DAC space (where halving is linear). Minimising
//      L(b) = sum_{p in B_k}(b - p)^2 + sum_{q in H_k}(b/2 - q)^2
//      yields b = (4*sum(B_k_srgb) + 2*sum(H_k_srgb))
//                 / (4*|B_k| + |H_k|)   (in sRGB).
//   4. Snap to OCS 12-bit nibbles (4 bits/channel), rebuild the EHB
//      palette, repeat.
//
// Empty slots are left unchanged. Iterations cap at `max_iters` or stop
// when slot drift falls below a small tolerance.
inline void refine_ehb_base_palette(std::span<Color3f> base_colors,
                                    std::span<const Color3f> image_pixels,
                                    bool snap_to_ocs = true,
                                    int max_iters = 8) {
    if (base_colors.size() < 32 || image_pixels.empty()) return;
    constexpr std::size_t kBaseN = 32;

    auto build_full = [&](std::span<const Color3f> base) {
        std::array<Color3f, 64> full{};
        for (std::size_t i = 0; i < kBaseN; ++i) full[i] = base[i];
        for (std::size_t i = 0; i < kBaseN; ++i) full[kBaseN + i] = half_brite(base[i]);
        return full;
    };

    auto oklab_of = [&](const Color3f& c) {
        return color_space::linear_to_oklab(c);
    };

    // OCS candidate set: when snap_to_ocs is true, the joint MSE
    // minimum has to be one of 4096 displayable colours. Brute-force
    // over all of them per slot, evaluating joint OKLab MSE with the
    // hardware-correct half_brite (per-nibble truncating shift). For
    // AGA (24-bit) we fall back to the closed-form sRGB centroid
    // (4·B+2·H)/(4|B|+|H|) since the candidate space is too large.
    //
    // OKLab table for both base candidates and their hardware halves
    // is built once per call (4096 × 2 entries). 32 slots × 4096
    // candidates × ~10 ops ≈ 1M ops per refine iteration — trivial.
    // Heap-allocate (each is 4096 × sizeof(OKLab) ≈ 48 KB) so we
    // don't blow the 64 KB WASM default stack.
    std::vector<color_space::OKLab> ocs_lab;
    std::vector<color_space::OKLab> ocs_halve_lab;
    if (snap_to_ocs) {
        ocs_lab.resize(4096);
        ocs_halve_lab.resize(4096);
        for (std::uint16_t code = 0; code < 4096; ++code) {
            Color3f c = ocs_to_linear(code);
            ocs_lab[code] = oklab_of(c);
            ocs_halve_lab[code] = oklab_of(half_brite(c));
        }
    }

    for (int it = 0; it < max_iters; ++it) {
        auto full_pal = build_full(base_colors);
        std::array<color_space::OKLab, 64> full_oklab{};
        for (std::size_t i = 0; i < 64; ++i) full_oklab[i] = oklab_of(full_pal[i]);

        // Per-slot OKLab sums and counts for the base bucket B_k
        // (pixels whose nearest is base[k]) and the half-brite bucket
        // H_k (pixels whose nearest is halve(base[k])).
        std::array<color_space::OKLab, kBaseN> sum_B_lab{}, sum_H_lab{};
        std::array<std::uint32_t, kBaseN> cnt_B{}, cnt_H{};
        // sRGB sums kept for the AGA fallback path.
        std::array<Color3f, kBaseN> sum_B_s{}, sum_H_s{};

        for (std::size_t i = 0; i < image_pixels.size(); ++i) {
            auto t = oklab_of(image_pixels[i]);
            std::size_t best = 0;
            float best_d = std::numeric_limits<float>::infinity();
            for (std::size_t k = 0; k < 64; ++k) {
                auto& e = full_oklab[k];
                float dL = t.L - e.L, da = t.a - e.a, db = t.b - e.b;
                float d  = dL * dL + da * da + db * db;
                if (d < best_d) { best_d = d; best = k; }
            }
            auto s = color_space::linear_to_srgb(image_pixels[i]).clamped();
            if (best < kBaseN) {
                sum_B_lab[best].L += t.L;
                sum_B_lab[best].a += t.a;
                sum_B_lab[best].b += t.b;
                sum_B_s[best].r += s.r;
                sum_B_s[best].g += s.g;
                sum_B_s[best].b += s.b;
                cnt_B[best] += 1;
            } else {
                auto k = best - kBaseN;
                sum_H_lab[k].L += t.L;
                sum_H_lab[k].a += t.a;
                sum_H_lab[k].b += t.b;
                sum_H_s[k].r += s.r;
                sum_H_s[k].g += s.g;
                sum_H_s[k].b += s.b;
                cnt_H[k] += 1;
            }
        }

        float drift = 0.0f;
        for (std::size_t k = 0; k < kBaseN; ++k) {
            if (cnt_B[k] + cnt_H[k] == 0) continue;
            Color3f new_lin{};
            if (snap_to_ocs) {
                // Joint OKLab MSE expanded:
                //   Σ_{i∈B} ||c - p_i||² + Σ_{i∈H} ||h - p_i||²
                // = |B|·||c||² - 2 c·Σ_B + Σ||p_B||²
                //   + |H|·||h||² - 2 h·Σ_H + Σ||p_H||²
                // Drop the constant Σ||p_i||² terms; argmin over the
                // remaining terms. Picks the OCS code whose (base,
                // halve(base)) pair best fits the joint cluster.
                float fcB = static_cast<float>(cnt_B[k]);
                float fcH = static_cast<float>(cnt_H[k]);
                std::uint16_t best_code = 0;
                float best_cost = std::numeric_limits<float>::infinity();
                for (std::uint16_t code = 0; code < 4096; ++code) {
                    auto& cl = ocs_lab[code];
                    auto& hl = ocs_halve_lab[code];
                    float cost_B = fcB * (cl.L*cl.L + cl.a*cl.a + cl.b*cl.b)
                                 - 2.0f * (cl.L*sum_B_lab[k].L
                                         + cl.a*sum_B_lab[k].a
                                         + cl.b*sum_B_lab[k].b);
                    float cost_H = fcH * (hl.L*hl.L + hl.a*hl.a + hl.b*hl.b)
                                 - 2.0f * (hl.L*sum_H_lab[k].L
                                         + hl.a*sum_H_lab[k].a
                                         + hl.b*sum_H_lab[k].b);
                    float cost = cost_B + cost_H;
                    if (cost < best_cost) { best_cost = cost; best_code = code; }
                }
                new_lin = ocs_to_linear(best_code);
            } else {
                // AGA path: closed-form sRGB centroid (assumes halve =
                // b/2; valid for AGA's 8-bit DAC where halve =
                // byte >> 1 ≈ byte/2 with rounding).
                std::uint32_t denom = 4u * cnt_B[k] + cnt_H[k];
                float fd = static_cast<float>(denom);
                Color3f new_srgb{
                    (4.0f * sum_B_s[k].r + 2.0f * sum_H_s[k].r) / fd,
                    (4.0f * sum_B_s[k].g + 2.0f * sum_H_s[k].g) / fd,
                    (4.0f * sum_B_s[k].b + 2.0f * sum_H_s[k].b) / fd,
                };
                new_srgb.r = std::clamp(new_srgb.r, 0.0f, 1.0f);
                new_srgb.g = std::clamp(new_srgb.g, 0.0f, 1.0f);
                new_srgb.b = std::clamp(new_srgb.b, 0.0f, 1.0f);
                new_lin = color_space::srgb_to_linear(new_srgb);
            }
            float dr = base_colors[k].r - new_lin.r;
            float dg = base_colors[k].g - new_lin.g;
            float db = base_colors[k].b - new_lin.b;
            drift += dr * dr + dg * dg + db * db;
            base_colors[k] = new_lin;
        }
        if (drift < 1e-6f) break;
    }
}

// "Extra OCS palette optimization" — 1-opt coordinate-descent local
// search on the 32-colour EHB base palette, ranked by full-image
// nearest-neighbour squared OKLab error. Same shape as ham_convert's
// EHB optimiser (decompiled from app/HAM_convert.java around lines
// 6857-7095): per pass, find the slot whose removal hurts least, then
// find the source-image colour that, dropped into that slot, lowers
// total error the most. Repeat until the chosen insertion candidate
// matches the previous pass's pick (slot converged) — then move on to
// the next slot. Half-brite copies are auto-rederived after every
// candidate change so the 64-effective gamut stays consistent.
//
// Cost: O(passes * 32 * (W*H*64) + passes * |candidates| * (W*H*64)).
// The candidate inner loop is the hot path and is parallelised; the
// removal loop is comparatively cheap. `palette_diversity_seed` is
// only used for tie-break determinism between equal-cost candidates;
// the search itself is deterministic.
inline void extra_ehb_optimization(std::span<Color3f> base_colors,
                                   std::span<const Color3f> image_pixels,
                                   bool snap_to_ocs,
                                   int max_passes,
                                   void(*parallel_for_fn)(std::size_t,
                                       std::function<void(std::size_t)>) =
                                           nullptr,
                                   std::function<void(float,
                                       std::string_view)> on_progress = {}) {
    if (base_colors.size() < 32 || image_pixels.empty()) return;
    constexpr std::size_t kBaseN = 32;
    auto N = image_pixels.size();

    // Pre-compute pixel OKLab; reused across every candidate evaluation.
    std::vector<color_space::OKLab> pix_lab(N);
    for (std::size_t i = 0; i < N; ++i)
        pix_lab[i] = color_space::linear_to_oklab(image_pixels[i]);

    auto eval_total_error = [&](const std::array<Color3f, 64>& full) {
        std::array<color_space::OKLab, 64> full_lab{};
        for (std::size_t k = 0; k < 64; ++k)
            full_lab[k] = color_space::linear_to_oklab(full[k]);
        double total = 0.0;
        for (std::size_t i = 0; i < N; ++i) {
            auto t = pix_lab[i];
            float best_d = std::numeric_limits<float>::infinity();
            for (std::size_t k = 0; k < 64; ++k) {
                auto& e = full_lab[k];
                float dL = t.L - e.L, da = t.a - e.a, db = t.b - e.b;
                float d  = dL * dL + da * da + db * db;
                if (d < best_d) best_d = d;
            }
            total += static_cast<double>(best_d);
        }
        return total;
    };

    auto build_full = [&](std::span<const Color3f, kBaseN> base) {
        std::array<Color3f, 64> full{};
        for (std::size_t i = 0; i < kBaseN; ++i) full[i] = base[i];
        for (std::size_t i = 0; i < kBaseN; ++i)
            full[kBaseN + i] = half_brite(base[i]);
        return full;
    };

    auto snap_one = [&](Color3f c) {
        return snap_to_ocs ? quantize_to_ocs(c) : c;
    };

    // Build candidate set: distinct snapped (chipset-precision) source
    // colours, ranked by histogram count and capped at `max_candidates`.
    // The cap matters: 320x180 photos can yield ~1000-1500 unique OCS
    // codes and the inner loop is the dominant cost. The decompiled
    // ham_convert path also caps at 4096 (the OCS gamut size).
    std::vector<Color3f> candidates;
    constexpr std::size_t kMaxCandidates = 512;
    {
        std::vector<std::uint32_t> keys(image_pixels.size());
        for (std::size_t i = 0; i < image_pixels.size(); ++i) {
            auto s = snap_one(image_pixels[i]);
            auto srgb = color_space::linear_to_srgb(s).clamped();
            keys[i] =
                (static_cast<std::uint32_t>(srgb.r * 255.0f + 0.5f) << 16) |
                (static_cast<std::uint32_t>(srgb.g * 255.0f + 0.5f) <<  8) |
                 static_cast<std::uint32_t>(srgb.b * 255.0f + 0.5f);
        }
        std::sort(keys.begin(), keys.end());
        std::vector<std::pair<std::uint32_t, std::uint32_t>> hist;  // {key, count}
        for (std::size_t i = 0; i < keys.size(); ) {
            std::size_t j = i + 1;
            while (j < keys.size() && keys[j] == keys[i]) ++j;
            hist.emplace_back(keys[i], static_cast<std::uint32_t>(j - i));
            i = j;
        }
        std::sort(hist.begin(), hist.end(),
            [](const auto& a, const auto& b) { return a.second > b.second; });
        if (hist.size() > kMaxCandidates) hist.resize(kMaxCandidates);
        candidates.reserve(hist.size());
        for (auto& [key, _] : hist) {
            std::uint8_t r = (key >> 16) & 0xFF;
            std::uint8_t g = (key >>  8) & 0xFF;
            std::uint8_t b =  key        & 0xFF;
            candidates.push_back(color_space::srgb_u8_to_linear(r, g, b));
        }
    }
    if (candidates.empty()) return;

    int slot_start = 0;
    std::size_t last_insert = static_cast<std::size_t>(-1);
    // Progress estimate: bound by max_passes * 32 outer iterations,
    // but the main loop may converge a slot in fewer iterations than
    // 32. Emit on every iteration; the slot_start advance gives the
    // user a roughly monotonic 0..1 readout.
    auto emit_progress = [&](int extra_subiter) {
        if (!on_progress) return;
        float frac = (static_cast<float>(slot_start) +
                      0.001f * static_cast<float>(extra_subiter)) /
                     static_cast<float>(kBaseN);
        on_progress(std::clamp(frac, 0.0f, 1.0f), "extra-ehb-opt");
    };
    int subiter = 0;
    if (on_progress) emit_progress(0);
    for (int pass = 0; pass < max_passes;) {
        // 1. Removal candidate: replace each slot k in [slot_start, 32)
        //    with its neighbour and pick the slot whose removal yields
        //    the lowest total error.
        int remove_slot = slot_start;
        double remove_err = std::numeric_limits<double>::infinity();
        std::array<Color3f, kBaseN> work{};
        for (std::size_t i = 0; i < kBaseN; ++i) work[i] = base_colors[i];
        for (int k = slot_start; k < static_cast<int>(kBaseN); ++k) {
            auto orig = work[static_cast<std::size_t>(k)];
            int neigh = (k > slot_start) ? k - 1 : k + 1;
            if (neigh >= static_cast<int>(kBaseN)) neigh = k;
            work[static_cast<std::size_t>(k)] =
                work[static_cast<std::size_t>(neigh)];
            auto full = build_full(std::span<const Color3f, kBaseN>(work));
            auto err = eval_total_error(full);
            work[static_cast<std::size_t>(k)] = orig;
            if (err < remove_err) {
                remove_err = err;
                remove_slot = k;
            }
        }

        // 2. Insertion candidate: try every distinct source colour in
        //    the removed slot, pick the one with lowest error.
        std::vector<double> errs(candidates.size(),
                                  std::numeric_limits<double>::infinity());
        auto eval_one = [&](std::size_t ci) {
            std::array<Color3f, kBaseN> tw{};
            for (std::size_t i = 0; i < kBaseN; ++i) tw[i] = base_colors[i];
            tw[static_cast<std::size_t>(remove_slot)] =
                snap_one(candidates[ci]);
            auto full = build_full(std::span<const Color3f, kBaseN>(tw));
            errs[ci] = eval_total_error(full);
        };
        if (parallel_for_fn) {
            parallel_for_fn(candidates.size(), eval_one);
        } else {
            for (std::size_t ci = 0; ci < candidates.size(); ++ci) eval_one(ci);
        }
        std::size_t best_insert = 0;
        for (std::size_t ci = 1; ci < candidates.size(); ++ci) {
            if (errs[ci] < errs[best_insert])
                best_insert = ci;
        }

        if (best_insert == last_insert) {
            // Slot converged — write its final value, swap to slot_start
            // so the remaining slots make progress, advance slot_start.
            base_colors[static_cast<std::size_t>(remove_slot)] =
                snap_one(candidates[best_insert]);
            if (remove_slot != slot_start) {
                std::swap(
                    base_colors[static_cast<std::size_t>(remove_slot)],
                    base_colors[static_cast<std::size_t>(slot_start)]);
            }
            ++slot_start;
            subiter = 0;
            last_insert = static_cast<std::size_t>(-1);
            ++pass;
            emit_progress(0);
            if (slot_start >= static_cast<int>(kBaseN)) break;
        } else {
            base_colors[static_cast<std::size_t>(remove_slot)] =
                snap_one(candidates[best_insert]);
            last_insert = best_insert;
            emit_progress(++subiter);
        }
    }
}

} // namespace png2amiga::palette
