#include "snes_io.hpp"
#include "snes_color.hpp"

#include <cstdio>
#include <filesystem>
#include <format>
#include <fstream>
#include <string>

namespace png2amiga::snes_io {

namespace {

Result<void> write_bytes(std::string_view path,
                         std::span<const std::uint8_t> bytes) {
    std::ofstream f(std::string(path), std::ios::binary);
    if (!f) return std::unexpected{Error{ErrorCode::write_failed,
        std::format("Failed to open for writing: {}", path)}};
    f.write(reinterpret_cast<const char*>(bytes.data()),
            static_cast<std::streamsize>(bytes.size()));
    if (!f) return std::unexpected{Error{ErrorCode::write_failed,
        std::format("Failed to write: {}", path)}};
    return {};
}

// Replace the trailing extension of `path` with `new_ext` (which must
// include the leading dot). Used to derive the .pal companion path.
std::string with_extension(std::string_view path, std::string_view new_ext) {
    std::filesystem::path p{std::string(path)};
    p.replace_extension(std::string(new_ext));
    return p.string();
}

void append_hex_byte(std::string& out, std::uint8_t b) {
    char buf[8];
    std::snprintf(buf, sizeof buf, "0x%02x", b);
    out += buf;
}

void append_hex_word(std::string& out, std::uint16_t w) {
    char buf[10];
    std::snprintf(buf, sizeof buf, "0x%04x", w);
    out += buf;
}

} // namespace

Result<void> write_snes_mode7_256(std::string_view out_path,
                                  std::span<const std::uint8_t> indices,
                                  std::span<const Color3f> palette,
                                  std::size_t width, std::size_t height) {
    if (indices.size() != width * height)
        return std::unexpected{Error{ErrorCode::invalid_png,
            "snes_mode7_256: indices size != width × height"}};
    if (palette.size() > 256)
        return std::unexpected{Error{ErrorCode::invalid_png,
            "snes_mode7_256: palette must have ≤ 256 entries"}};

    if (auto r = write_bytes(out_path, indices); !r) return r;

    // Palette: 256 BGR555 words, little-endian. Pad with zeros if the
    // palette is shorter than 256.
    std::vector<std::uint8_t> pal_bytes(256 * 2, 0);
    for (std::size_t i = 0; i < palette.size(); ++i) {
        std::uint16_t w = snes_color::to_bgr555_word(palette[i]);
        pal_bytes[i * 2 + 0] = static_cast<std::uint8_t>(w & 0xFF);
        pal_bytes[i * 2 + 1] = static_cast<std::uint8_t>((w >> 8) & 0xFF);
    }
    auto pal_path = with_extension(out_path, ".pal");
    return write_bytes(pal_path, pal_bytes);
}

Result<void> write_snes_mode7_direct(std::string_view out_path,
                                     std::span<const std::uint8_t> pixels,
                                     std::size_t width, std::size_t height) {
    if (pixels.size() != width * height)
        return std::unexpected{Error{ErrorCode::invalid_png,
            "snes_mode7_direct: pixels size != width × height"}};
    return write_bytes(out_path, pixels);
}

Result<std::vector<std::uint8_t>> encode_snes_mode7_256_header(
    std::span<const std::uint8_t> indices,
    std::span<const Color3f> palette,
    std::size_t width, std::size_t height,
    std::string_view symbol) {

    if (indices.size() != width * height)
        return std::unexpected{Error{ErrorCode::invalid_png,
            "encode_snes_mode7_256_header: indices size mismatch"}};

    std::string out;
    out += std::format("// SNES Mode 7 256-colour data — {}x{} pixels, {} palette entries\n",
                       width, height, palette.size());
    out += std::format("// Generated by png2amiga.\n\n");
    out += std::format("#define {}_WIDTH  {}\n", symbol, width);
    out += std::format("#define {}_HEIGHT {}\n\n", symbol, height);

    // Pixel array
    out += std::format("const unsigned char {}_pixels[{}] = {{\n",
                       symbol, indices.size());
    for (std::size_t i = 0; i < indices.size(); ++i) {
        if (i % 16 == 0) out += "    ";
        append_hex_byte(out, indices[i]);
        if (i + 1 < indices.size()) out += ',';
        if (i % 16 == 15 || i + 1 == indices.size()) out += '\n';
        else out += ' ';
    }
    out += "};\n\n";

    // Palette as 16-bit BGR555 words — pad to 256 entries.
    out += std::format("const unsigned short {}_palette[256] = {{\n", symbol);
    for (std::size_t i = 0; i < 256; ++i) {
        std::uint16_t w = (i < palette.size())
            ? snes_color::to_bgr555_word(palette[i]) : 0;
        if (i % 8 == 0) out += "    ";
        append_hex_word(out, w);
        if (i + 1 < 256) out += ',';
        if (i % 8 == 7) out += '\n';
        else out += ' ';
    }
    out += "};\n";

    return std::vector<std::uint8_t>(out.begin(), out.end());
}

Result<std::vector<std::uint8_t>> encode_snes_mode7_direct_header(
    std::span<const std::uint8_t> pixels,
    std::size_t width, std::size_t height,
    std::string_view symbol) {

    if (pixels.size() != width * height)
        return std::unexpected{Error{ErrorCode::invalid_png,
            "encode_snes_mode7_direct_header: pixels size mismatch"}};

    std::string out;
    out += std::format("// SNES Mode 7 Direct Color (RGB443) — {}x{} pixels\n",
                       width, height);
    out += std::format("// Pixel byte format: bbgggrrr (low bits; hardware sub-palette\n");
    out += std::format("//                     supplies the high R/G/B bits).\n");
    out += std::format("// Generated by png2amiga.\n\n");
    out += std::format("#define {}_WIDTH  {}\n", symbol, width);
    out += std::format("#define {}_HEIGHT {}\n\n", symbol, height);
    out += std::format("const unsigned char {}_pixels[{}] = {{\n",
                       symbol, pixels.size());
    for (std::size_t i = 0; i < pixels.size(); ++i) {
        if (i % 16 == 0) out += "    ";
        append_hex_byte(out, pixels[i]);
        if (i + 1 < pixels.size()) out += ',';
        if (i % 16 == 15 || i + 1 == pixels.size()) out += '\n';
        else out += ' ';
    }
    out += "};\n";

    return std::vector<std::uint8_t>(out.begin(), out.end());
}

} // namespace png2amiga::snes_io
