# cmake -DINPUT=path -DOUTPUT=path -DSYMBOL=name -P EmbedBinary.cmake
#
# Generates a header that embeds the input file as a constexpr byte
# array under the given symbol name. Used to bake the compiled
# Metal library (.metallib) into the png2amiga binary so the
# runtime is self-contained on macOS without a sidecar file.
#
# Output layout:
#   inline constexpr unsigned char SYMBOL[] = { 0xNN, 0xNN, ... };
#   inline constexpr std::size_t   SYMBOL_size = sizeof(SYMBOL);

if(NOT INPUT OR NOT OUTPUT OR NOT SYMBOL)
    message(FATAL_ERROR "EmbedBinary.cmake: INPUT, OUTPUT, SYMBOL all required")
endif()

file(READ ${INPUT} _hex HEX)
string(LENGTH "${_hex}" _hex_len)
math(EXPR _bytes "${_hex_len} / 2")

# Build the comma-separated list of 0xNN tokens. We chunk the work
# in groups of 16 bytes per line to keep the header readable and
# the per-iteration string-build cost reasonable.
set(_arr "")
set(_i 0)
while(_i LESS _hex_len)
    string(SUBSTRING "${_hex}" ${_i} 2 _b)
    string(APPEND _arr "0x${_b},")
    math(EXPR _i "${_i} + 2")
    math(EXPR _line_pos "(${_i} / 2) % 16")
    if(_line_pos EQUAL 0)
        string(APPEND _arr "\n    ")
    endif()
endwhile()

file(WRITE ${OUTPUT}
"// Auto-generated by cmake/EmbedBinary.cmake. Do not edit.\n"
"#pragma once\n"
"#include <cstddef>\n"
"\n"
"inline constexpr unsigned char ${SYMBOL}[] = {\n    ${_arr}\n};\n"
"inline constexpr std::size_t ${SYMBOL}_size = ${_bytes};\n"
)
