import { test, expect } from '@playwright/test'

test('C64 cell refinement selects and restricts error diffusion dithers', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.p-progressspinner')).toHaveCount(0, { timeout: 30_000 })
  await page.getByRole('combobox').nth(0).click()
  await page.getByRole('option', { name: 'Commodore 64 / VIC-II', exact: true }).click()
  const trigger = page.locator('.dither-trigger')
  const cards = page.locator('.dither-card')
  await trigger.click()
  await cards.filter({ hasText: 'Bayer 4×4' }).click()
  const refine = page.getByLabel('Cell refine', { exact: true })
  await refine.check()
  await expect(trigger).toContainText('Floyd– Steinberg')
  await trigger.click()
  await expect(cards).toHaveCount(9)
  await expect(cards.filter({ hasText: /Bayer|Gilbert|DBS/ })).toHaveCount(0)
  await cards.filter({ hasText: 'Atkinson' }).click()
  await refine.uncheck()
  await refine.check()
  await expect(trigger).toContainText('Atkinson')
  await refine.uncheck()
  await trigger.click()
  await expect(cards.filter({ hasText: 'Bayer 4×4' })).toBeVisible()
})

test('cell refinement clears when the CGA metric becomes unsupported', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.p-progressspinner')).toHaveCount(0, { timeout: 30_000 })
  const refine = page.getByLabel('Cell refine', { exact: true })
  await expect(refine).toHaveCount(0)

  await page.getByRole('combobox').nth(0).click()
  await page.getByRole('option', { name: 'IBM PC CGA (fixed palette)', exact: true }).click()
  await expect(refine).toHaveCount(0)
  await page.getByRole('combobox').nth(1).click()
  await page.getByRole('option', { name: 'CGA Text 80x100', exact: true }).click()
  await expect(refine).toBeVisible()
  await refine.check()

  await page.getByRole('combobox').filter({ hasText: 'Pappas-Neuhoff' }).click()
  await page.getByRole('option', { name: 'Per-pixel MSE', exact: true }).click()
  await expect(refine).toHaveCount(0)
  await page.getByRole('combobox').filter({ hasText: 'Per-pixel MSE' }).click()
  await page.getByRole('option', { name: 'Pappas-Neuhoff', exact: true }).click()
  await expect(refine).not.toBeChecked()

  await refine.check()
  await page.getByRole('combobox').nth(1).click()
  await page.getByRole('option', { name: 'CGA 320x200', exact: true }).click()
  await expect(refine).toHaveCount(0)
  await page.getByRole('combobox').nth(1).click()
  await page.getByRole('option', { name: 'CGA Text 80x100', exact: true }).click()
  await expect(refine).not.toBeChecked()
})
