// Generated by png2amiga-assets (map) — do not edit.
// Tilemap: level_1_1
// References tile pool: assets::tiles_1_1
#pragma once

#include <array>
#include <cstdint>

#include "tiles_1_1.hpp"

namespace assets::level_1_1 {

using assets::tiles_1_1::tile_w;
using assets::tiles_1_1::tile_h;
using assets::tiles_1_1::depth;
using assets::tiles_1_1::bytes_per_row;
using assets::tiles_1_1::tile_bytes;
using assets::tiles_1_1::num_tiles;
using assets::tiles_1_1::palette_size;
using assets::tiles_1_1::tile_ptr;
using assets::tiles_1_1::palette;

inline constexpr unsigned map_w     = 326;
inline constexpr unsigned map_h     = 102;
inline constexpr unsigned num_cells = 33252;

struct MapCell {
    std::uint16_t raw;
    [[nodiscard]] constexpr std::uint16_t index() const noexcept {
        return static_cast<std::uint16_t>(raw & 0x3FFFu);
    }
    [[nodiscard]] constexpr bool h_flip() const noexcept {
        return (raw & 0x8000u) != 0;
    }
    [[nodiscard]] constexpr bool v_flip() const noexcept {
        return (raw & 0x4000u) != 0;
    }
};
static_assert(sizeof(MapCell) == 2);

extern const std::array<MapCell, num_cells> tilemap;

[[nodiscard]] constexpr MapCell cell_at(unsigned x, unsigned y) noexcept {
    return tilemap[y * map_w + x];
}

} // namespace assets::level_1_1
