// Generated by png2amiga-assets (tileset) — do not edit.
// Shared tile pool for: tiles_1_1
#pragma once

#include <array>
#include <cstdint>

namespace assets::tiles_1_1 {

inline constexpr unsigned tile_w         = 16;
inline constexpr unsigned tile_h         = 16;
inline constexpr unsigned depth          = 4;
inline constexpr unsigned bytes_per_row  = 2;
inline constexpr unsigned tile_bytes     = 128;
inline constexpr unsigned num_tiles      = 518;
inline constexpr unsigned palette_size   = 16;

extern const std::array<std::uint16_t, num_tiles * (tile_bytes / 2)> tiles_data;
extern const std::array<std::uint16_t, palette_size> palette;

[[nodiscard]] constexpr const std::uint16_t* tile_ptr(std::uint16_t idx) noexcept {
    return tiles_data.data() + static_cast<std::size_t>(idx) * (tile_bytes / 2);
}

} // namespace assets::tiles_1_1
