<script setup lang="ts">
import { computed, nextTick, useTemplateRef } from 'vue'
import Popover from 'primevue/popover'
import Button from 'primevue/button'

interface DitherItem { value: string; label: string }
interface DitherGroup { label: string; items: DitherItem[] }

const props = defineProps<{
  modelValue: string
  groups: DitherGroup[]
}>()

const emit = defineEmits<{ 'update:modelValue': [value: string] }>()

const popoverRef = useTemplateRef<InstanceType<typeof Popover>>('popoverRef')
const galleryRef = useTemplateRef<HTMLElement>('galleryRef')

// When the popover opens, scroll the currently-selected card into view so
// the user lands on their current pick instead of at the top of the list.
// Sets scrollTop on the gallery container directly (not scrollIntoView)
// to avoid scrolling the outer page when the popover is large.
async function onPopoverShow(): Promise<void> {
  await nextTick()
  const root = galleryRef.value
  const selected = root?.querySelector<HTMLElement>('.dither-card.selected')
  if (!root || !selected) return
  const target = selected.offsetTop - (root.clientHeight - selected.offsetHeight) / 2
  root.scrollTop = Math.max(0, target)
}

// Thumbnails generated by scripts/gen-dither-thumbs.mjs into
// web/public/dither-thumbs/ — Vite serves them under BASE_URL.
function thumbUrl(value: string): string {
  return `${import.meta.env.BASE_URL}dither-thumbs/${value}.png`
}

const flatItems = computed(() =>
  props.groups.flatMap(g => g.items)
)

const currentLabel = computed(() => {
  const found = flatItems.value.find(d => d.value === props.modelValue)
  // Card labels may embed `\n` for forced wrapping in the gallery; the
  // trigger always shows a single line, so collapse whitespace here.
  return (found?.label ?? props.modelValue).replaceAll(/\s+/g, ' ')
})

function select(value: string): void {
  emit('update:modelValue', value)
  popoverRef.value?.hide()
}

function togglePopover(evt: Event): void {
  popoverRef.value?.toggle(evt)
}

function cycle(direction: number): void {
  const vals = flatItems.value.map(d => d.value)
  const idx = vals.indexOf(props.modelValue)
  const next = (idx + direction + vals.length) % vals.length
  const v = vals[next]
  if (v) emit('update:modelValue', v)
}
</script>

<template>
  <div class="dither-gallery-wrap flex gap-1 align-items-center">
    <button
      type="button"
      class="dither-trigger flex-1"
      @click="togglePopover"
    >
      <img :src="thumbUrl(modelValue)" alt="" class="dither-trigger-thumb" />
      <span class="dither-trigger-label">{{ currentLabel }}</span>
      <i class="pi pi-chevron-down dither-trigger-caret" />
    </button>
    <div class="flex flex-column" style="gap:1px">
      <Button icon="pi pi-chevron-up" severity="secondary" text size="small"
        :pt="{ root: { style: 'min-width:0;width:1.2rem;height:0.85rem;padding:0' } }"
        @click="cycle(-1)" />
      <Button icon="pi pi-chevron-down" severity="secondary" text size="small"
        :pt="{ root: { style: 'min-width:0;width:1.2rem;height:0.85rem;padding:0' } }"
        @click="cycle(1)" />
    </div>
    <Popover ref="popoverRef" @show="onPopoverShow">
      <div ref="galleryRef" class="dither-gallery">
        <section v-for="g in groups" :key="g.label" class="dither-group">
          <h4 class="dither-group-label">{{ g.label }}</h4>
          <div class="dither-grid">
            <button
              v-for="d in g.items"
              :key="d.value"
              type="button"
              class="dither-card"
              :class="{ selected: d.value === modelValue }"
              :title="d.label"
              @click="select(d.value)"
            >
              <img :src="thumbUrl(d.value)" alt="" class="dither-card-thumb" />
              <span class="dither-card-label">{{ d.label }}</span>
            </button>
          </div>
        </section>
      </div>
    </Popover>
  </div>
</template>

<style scoped>
.dither-trigger {
  display: flex;
  align-items: center;
  gap: 0.4rem;
  padding: 0.25rem 0.4rem;
  min-width: 0;
  background: var(--p-select-background);
  color: var(--p-select-color);
  border: 1px solid var(--p-select-border-color);
  border-radius: var(--p-border-radius-sm, 4px);
  cursor: pointer;
  font: inherit;
  text-align: left;
  height: 2rem;
}
.dither-trigger:hover { border-color: var(--p-select-hover-border-color); }
.dither-trigger:focus-visible {
  outline: 2px solid var(--p-focus-ring-color, #60a5fa);
  outline-offset: 1px;
}
.dither-trigger-thumb {
  width: 22px;
  height: 22px;
  image-rendering: pixelated;
  flex: 0 0 auto;
  border: 1px solid #2a2a2a;
}
.dither-trigger-label {
  flex: 1 1 auto;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  font-size: 0.78rem;
}
.dither-trigger-caret { font-size: 0.6rem; opacity: 0.6; flex: 0 0 auto; }

.dither-gallery {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  max-height: 70vh;
  /* `scroll` (vs `auto`) forces the track to always render so the
     popup's scrollability is visually obvious — `auto` only paints
     the bar mid-scroll on macOS / iOS, which made the popup look
     fixed-height even though it actually did scroll. */
  overflow-y: scroll;
  padding: 0.25rem;
  min-width: 640px;
}
/* Make the always-on track readable on dark backgrounds — macOS
   default overlay scrollbars are nearly invisible at rest. */
.dither-gallery::-webkit-scrollbar { width: 10px; }
.dither-gallery::-webkit-scrollbar-track {
  background: rgba(255, 255, 255, 0.04);
  border-radius: 5px;
}
.dither-gallery::-webkit-scrollbar-thumb {
  background: rgba(255, 255, 255, 0.25);
  border-radius: 5px;
}
.dither-gallery::-webkit-scrollbar-thumb:hover {
  background: rgba(255, 255, 255, 0.40);
}
/* Firefox — `scrollbar-color` plus `scrollbar-width: thin` keeps it
   visible without inflating the popup geometry. */
.dither-gallery {
  scrollbar-width: thin;
  scrollbar-color: rgba(255, 255, 255, 0.25) rgba(255, 255, 255, 0.04);
}
.dither-group-label {
  margin: 0 0 0.35rem;
  font-size: 0.7rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--p-text-muted-color, #999);
}
.dither-grid {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 0.35rem;
}
.dither-card {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.35rem 0.5rem;
  background: transparent;
  border: 1px solid transparent;
  border-radius: var(--p-border-radius-sm, 4px);
  cursor: pointer;
  font: inherit;
  color: inherit;
  text-align: left;
  width: 100%;
  min-width: 0;
}
.dither-card:hover {
  background: var(--p-select-option-focus-background, #2a2a2a);
}
.dither-card.selected {
  background: var(--p-select-option-selected-background, #1e3a5f);
  border-color: var(--p-primary-color, #60a5fa);
}
.dither-card:focus-visible {
  outline: 2px solid var(--p-focus-ring-color, #60a5fa);
  outline-offset: -1px;
}
.dither-card-thumb {
  width: 64px;
  height: 64px;
  image-rendering: pixelated;
  flex: 0 0 64px;
  border: 1px solid #2a2a2a;
}
.dither-card-label {
  flex: 1 1 auto;
  min-width: 0;
  font-size: 0.78rem;
  line-height: 1.15;
  white-space: pre-line;
  overflow-wrap: break-word;
}
</style>
