// Generated by png2amiga-assets — do not edit.
// Source tilesheet: level_3_1
#pragma once

#include <array>
#include <cstdint>

namespace assets::level_3_1 {

inline constexpr unsigned tile_w         = 16;
inline constexpr unsigned tile_h         = 16;
inline constexpr unsigned depth          = 5;
inline constexpr unsigned bytes_per_row  = 2;
inline constexpr unsigned tile_bytes     = 160;
inline constexpr unsigned num_tiles      = 143;
inline constexpr unsigned map_w          = 40;
inline constexpr unsigned map_h          = 6;
inline constexpr unsigned num_cells      = 240;
inline constexpr unsigned palette_size   = 17;

struct MapCell {
    std::uint16_t raw;
    [[nodiscard]] constexpr std::uint16_t index() const noexcept {
        return static_cast<std::uint16_t>(raw & 0x3FFFu);
    }
    [[nodiscard]] constexpr bool h_flip() const noexcept {
        return (raw & 0x8000u) != 0;
    }
    [[nodiscard]] constexpr bool v_flip() const noexcept {
        return (raw & 0x4000u) != 0;
    }
};
static_assert(sizeof(MapCell) == 2);

extern const std::array<std::uint16_t, num_tiles * (tile_bytes / 2)> tiles_data;
extern const std::array<MapCell, num_cells> tilemap;
extern const std::array<std::uint16_t, palette_size> palette;

[[nodiscard]] constexpr const std::uint16_t* tile_ptr(std::uint16_t idx) noexcept {
    return tiles_data.data() + static_cast<std::size_t>(idx) * (tile_bytes / 2);
}

[[nodiscard]] constexpr MapCell cell_at(unsigned x, unsigned y) noexcept {
    return tilemap[y * map_w + x];
}

} // namespace assets::level_3_1
